import { defineModuleManifest } from '@/common/config/moduleManifest';

export const amzHubManifest = defineModuleManifest({
  moduleId: 'amz_hub',
  panelId: 'panel-amz_hub',
  routes: [
    {
      key: 'OVERVIEW',
      routeId: 'amz_hub_overview',
      path: '/amz-hub',
      label: '智库总览',
      icon: 'fas fa-th-large',
      loaderPath: './views/overview/index.ts',
    },
    {
      key: 'EU_INSIGHTS',
      routeId: 'amz_eu_insights',
      path: '/amz-hub/knowledge/eu-insights',
      label: '市场洞察',
      icon: 'fas fa-globe-europe',
      category: 'knowledge',
      loaderPath: './views/knowledge/eu_insights/index.ts',
    },
    {
      key: 'SEO_STRATEGY',
      routeId: 'amz_seo_strategy',
      path: '/amz-hub/knowledge/seo-strategy',
      label: 'SEO 策略',
      icon: 'fas fa-magnifying-glass-chart',
      category: 'knowledge',
      loaderPath: './views/knowledge/seo_strategy/index.ts',
    },
    {
      key: 'ECOSYSTEM',
      routeId: 'amz_ecosystem',
      path: '/amz-hub/knowledge/ecosystem',
      label: 'A10 & COSMO',
      icon: 'fas fa-network-wired',
      category: 'knowledge',
      loaderPath: './views/knowledge/ecosystem/index.ts',
    },
    {
      key: 'QUALITY_LISTING',
      routeId: 'amz_quality_listing',
      path: '/amz-hub/practice/quality-listing',
      label: '教你打造优质Listing',
      icon: 'fas fa-star',
      category: 'practice',
      loaderPath: './views/practice/quality_listing/index.ts',
    },
    {
      key: 'MARKETING_CALENDAR',
      routeId: 'amz_marketing_calendar',
      path: '/amz-hub/practice/marketing-calendar',
      label: 'EU营销日历',
      icon: 'fas fa-calendar-alt',
      category: 'practice',
      loaderPath: './views/practice/marketing_calendar/index.ts',
    },
    {
      key: 'PROMO_ACTIVITIES',
      routeId: 'amz_promo_activities',
      path: '/amz-hub/practice/promo-activities',
      label: '促销活动',
      icon: 'fa-solid fa-gift',
      category: 'practice',
      loaderPath: './views/practice/promo_activities/index.ts',
    },
    {
      key: 'PROMO_TOOLS',
      routeId: 'amz_promo_tools',
      path: '/amz-hub/practice/promo-tools',
      label: '促销工具',
      icon: 'fas fa-tools',
      category: 'practice',
      loaderPath: './views/practice/promo_tools/index.ts',
    },
    {
      key: 'NEW_PRODUCT_30DAYS',
      routeId: 'amz_new_product_30days',
      path: '/amz-hub/advanced/new-product-30days',
      label: '新品30天极速突围',
      icon: 'fas fa-rocket',
      category: 'advanced',
      loaderPath: './views/advanced/new_product_30days/index.ts',
    },
    {
      key: 'CONVERSION_OPTIMIZATION',
      routeId: 'amz_conversion_optimization',
      path: '/amz-hub/advanced/conversion-optimization',
      label: '链接转化率低自查优化',
      icon: 'fas fa-chart-line',
      category: 'advanced',
      loaderPath: './views/advanced/conversion_optimization/index.ts',
    },
    {
      key: 'MATURE_PHASE',
      routeId: 'amz_mature_phase',
      path: '/amz-hub/advanced/mature-phase',
      label: '成熟期运营策略',
      icon: 'fas fa-trophy',
      category: 'advanced',
      loaderPath: './views/advanced/mature_phase/index.ts',
    },
  ],
} as const);
