import { defineModuleManifest } from "@/common/config/moduleManifest";

export const amzHubManifest = defineModuleManifest({
  moduleId: "amz_hub_core",
  panelId: "panel-amz_hub",
  routes: [
    {
      key: "OVERVIEW",
      routeId: "amz_hub_overview",
      label: "智库总览",
      icon: "fas fa-th-large",
      loader: () => import("./views/overview/index"),
    },
    {
      key: "EU_INSIGHTS",
      routeId: "amz_eu_insights",
      label: "市场洞察",
      icon: "fas fa-globe-europe",
      category: "knowledge",
      loader: () => import("./views/knowledge/eu_insights/index"),
    },
    {
      key: "SEO_STRATEGY",
      routeId: "amz_seo_strategy",
      label: "SEO 策略",
      icon: "fas fa-magnifying-glass-chart",
      category: "knowledge",
      loader: () => import("./views/knowledge/seo_strategy/index"),
    },
    {
      key: "ECOSYSTEM",
      routeId: "amz_ecosystem",
      label: "A10 & COSMO",
      icon: "fas fa-network-wired",
      category: "knowledge",
      loader: () => import("./views/knowledge/ecosystem/index"),
    },
    {
      key: "QUALITY_LISTING",
      routeId: "amz_quality_listing",
      label: "教你打造优质Listing",
      icon: "fas fa-star",
      category: "practice",
      loader: () => import("./views/practice/quality_listing/index"),
    },
    {
      key: "MARKETING_CALENDAR",
      routeId: "amz_marketing_calendar",
      label: "EU营销日历",
      icon: "fas fa-calendar-alt",
      category: "practice",
      loader: () => import("./views/practice/marketing_calendar/index"),
    },
    {
      key: "PROMO_ACTIVITIES",
      routeId: "amz_promo_activities",
      label: "促销活动",
      icon: "fa-solid fa-gift",
      category: "practice",
      loader: () => import("./views/practice/promo_activities/index"),
    },
    {
      key: "PROMO_TOOLS",
      routeId: "amz_promo_tools",
      label: "促销工具",
      icon: "fas fa-tools",
      category: "practice",
      loader: () => import("./views/practice/promo_tools/index"),
    },
    {
      key: "NEW_PRODUCT_30DAYS",
      routeId: "amz_new_product_30days",
      label: "新品30天极速突围",
      icon: "fas fa-rocket",
      category: "advanced",
      loader: () => import("./views/advanced/new_product_30days/index"),
    },
    {
      key: "CONVERSION_OPTIMIZATION",
      routeId: "amz_conversion_optimization",
      label: "链接转化率低自查优化",
      icon: "fas fa-chart-line",
      category: "advanced",
      loader: () => import("./views/advanced/conversion_optimization/index"),
    },
  ],
} as const);
