import { defineModuleManifest } from "@/common/config/moduleManifest";

export const appCenterManifest = defineModuleManifest({
  moduleId: "app_center",
  panelId: "panel-app_center",
  routes: [
    {
      key: "OVERVIEW",
      routeId: "app_center_overview",
      label: "应用总览",
      icon: "fas fa-th-large",
    },
    {
      key: "SCRAPER",
      routeId: "scraper",
      moduleId: "master_analysis",
      label: "数据采集",
      icon: "fas fa-spider",
      category: "master_analysis",
    },
    {
      key: "AI_ANALYSIS",
      routeId: "ai_analysis",
      moduleId: "master_analysis",
      label: "AI智能分析",
      icon: "fas fa-brain",
      category: "master_analysis",
    },
    {
      key: "PROMPTLAB",
      routeId: "promptlab",
      moduleId: "master_analysis",
      label: "Prompt 生成",
      icon: "fas fa-wand-magic-sparkles",
      category: "master_analysis",
    },
    {
      key: "PLAYGROUND",
      routeId: "playground",
      moduleId: "playground",
      label: "Deep Chat",
      icon: "fa-regular fa-comments",
      category: "playground",
    },
    {
      key: "KW_INPUT",
      routeId: "kw_input",
      moduleId: "keyword_tracker",
      label: "输入模块",
      icon: "fas fa-keyboard",
      category: "keyword_tracker",
    },
    {
      key: "KW_PROCESS",
      routeId: "kw_process",
      moduleId: "keyword_tracker",
      label: "处理模块",
      icon: "fas fa-cogs",
      category: "keyword_tracker",
    },
    {
      key: "KW_ANALYSIS",
      routeId: "kw_analysis",
      moduleId: "keyword_tracker",
      label: "分析统计",
      icon: "fas fa-chart-pie",
      category: "keyword_tracker",
    },
    {
      key: "KW_HISTORY",
      routeId: "kw_history",
      moduleId: "keyword_tracker",
      label: "历史快照",
      icon: "fas fa-clock-rotate-left",
      category: "keyword_tracker",
    },
    {
      key: "PPC_SEARCH_TERMS",
      routeId: "ppc_search_terms",
      moduleId: "ppc_tools",
      label: "PPC 搜索词分析器",
      icon: "fas fa-magnifying-glass-dollar",
      category: "ppc_tools",
    },
  ],
} as const);
