import { defineModuleManifest } from "@/common/config/moduleManifest";

export const sopsManifest = defineModuleManifest({
  moduleId: "sops",
  panelId: "panel-sops",
  routes: [
    {
      key: "OVERVIEW",
      routeId: "sops_overview",
      label: "SOP 总览",
      icon: "fas fa-th-large",
      viewPath: "/src/modules/sops/sops.html",
    },
    {
      key: "NPI_TRACKER",
      routeId: "sops_npi_tracker",
      label: "新品生命周期跟踪",
      icon: "fas fa-seedling",
      category: "growth",
    },
    {
      key: "LISTING_SEO",
      routeId: "sops_listing_seo",
      label: "Listing 极致优化 (SEO)",
      icon: "fas fa-magnifying-glass-chart",
      category: "growth",
    },
    {
      key: "PPC_ADVERTISING",
      routeId: "sops_ppc_advertising",
      label: "PPC 广告投放与优化",
      icon: "fas fa-chart-line",
      category: "growth",
    },
    {
      key: "RESTRICTED_WORDS",
      routeId: "sops_restricted_words",
      label: "欧洲本土化高危词库",
      icon: "fas fa-book-dead",
      category: "growth",
    },
    {
      key: "PROMOTION_SUBMISSION",
      routeId: "sops_promotion_submission",
      label: "促销活动提报",
      icon: "fas fa-tags",
      category: "growth",
    },
    {
      key: "COMPETITOR_MONITORING",
      routeId: "sops_competitor_monitoring",
      label: "竞品监控与分析",
      icon: "fas fa-binoculars",
      category: "growth",
    },
    {
      key: "FBA_SHIPPING",
      routeId: "sops_fba_shipping",
      label: "FBA 发货标准操作",
      icon: "fas fa-truck-fast",
      category: "backend",
    },
    {
      key: "PROCUREMENT_QC",
      routeId: "sops_procurement_qc",
      label: "采购与质检 (QC)",
      icon: "fas fa-clipboard-check",
      category: "backend",
    },
    {
      key: "INVENTORY_REPLENISHMENT",
      routeId: "sops_inventory_replenishment",
      label: "库存预警与补货",
      icon: "fas fa-cubes",
      category: "backend",
    },
    {
      key: "ACCOUNT_SECURITY",
      routeId: "sops_account_security",
      label: "账号登录与环境安全",
      icon: "fas fa-shield-halved",
      category: "safety",
    },
    {
      key: "PERMISSION_MANAGEMENT",
      routeId: "sops_permission_management",
      label: "后台权限管理",
      icon: "fas fa-user-lock",
      category: "safety",
    },
    {
      key: "BRAND_INFRINGEMENT",
      routeId: "sops_brand_infringement",
      label: "品牌与侵权审核",
      icon: "fas fa-trademark",
      category: "safety",
    },
    {
      key: "PERFORMANCE_NOTIFICATION",
      routeId: "sops_performance_notification",
      label: "绩效通知处理",
      icon: "fas fa-bell",
      category: "safety",
    },
    {
      key: "PRODUCT_COMPLIANCE",
      routeId: "sops_product_compliance",
      label: "敏感产品合规销售",
      icon: "fas fa-file-shield",
      category: "safety",
    },
    {
      key: "EU_GPSR_COMPLIANCE",
      routeId: "sops_eu_gpsr_compliance",
      label: "欧洲GPSR合规",
      icon: "fa-solid fa-shield-dog",
      category: "safety",
    },
    {
      key: "EMAIL_TEMPLATES",
      routeId: "sops_email_templates",
      label: "邮件回复模板",
      icon: "fas fa-envelope-open-text",
      category: "service",
    },
    {
      key: "NEGATIVE_REVIEW",
      routeId: "sops_negative_review",
      label: "差评处理与分析",
      icon: "fas fa-comment-dots",
      category: "service",
    },
    {
      key: "QA_MAINTENANCE",
      routeId: "sops_qa_maintenance",
      label: "QA 问答维护",
      icon: "fas fa-comments",
      category: "service",
    },
  ],
} as const);
