// src/types/index.ts
// ================================================================
// 类型定义统一导出
// ================================================================

// API 响应类型
export type {
  ApiResponse,
  ApiError,
  PaginatedResponse,
  LLMMessage,
  LLMChatCompletionResponse,
  LLMStreamChunk,
  LLMModel,
  LLMModelsResponse,
  LLMErrorResponse,
  AmazonProductData,
  ScraperResponse,
  AnalysisSection,
  AnalysisReportResponse,
  PerformanceMetric,
  PerformanceReportResponse,
  WebVitalsResponse,
  ErrorRecordResponse,
  ErrorStatsResponse,
  AnalyticsEventResponse,
  AnalyticsStatsResponse,
  StorageResponse,
  ConfigResponse,
  LLMProviderConfigResponse,
  HealthCheckResponse,
  BatchOperationResult,
} from './api';

// 状态类型
export type {
  UIState,
  ScraperSite,
  ScraperStatus,
  ScrapedDataItem,
  ScraperState,
  ReportType,
  ReportData,
  AnalysisState,
  PromptHistoryItem,
  TargetMarket,
  ToneStyle,
  UserProductProfile,
  PromptInputs,
  PromptLabState,
  KeywordData,
  TrackingData,
  KeywordTrackerSettings,
  ParagraphData,
  KeywordTrackerState,
  UserInfo,
  UserPreferences,
  UserState,
  LLMProviderConfig,
  ProxyConfig,
  SettingsState,
  MasterPromptState,
  AppState,
  StatePath,
  NestedKeyOf,
  TypedStatePath,
  PathValue,
  UIPath,
  ScraperPath,
  AnalysisPath,
  PromptLabPath,
  KeywordTrackerPath,
  ValidStatePath,
  StateActionType,
  StateAction,
  BatchUpdateAction,
  BatchUpdateOptions,
  StateSubscriber,
  StateMiddleware,
  IStateManager,
  PersistStrategy,
  PersistConfig,
  IPersistMiddleware,
  StateSchema,
  StateHistory,
} from './state';

// 服务接口类型
export type {
  ILoggerService,
  IConfigService,
  IHttpService,
  IStorageService,
  IErrorService,
  IPerformanceService,
  IAnalyticsService,
} from './services';

// 业务模块类型
export type { AnalysisReport, AnalysisResult } from './modules-business';
