// 欧洲本土化高危词库常量
// 基于亚马逊欧洲站多年运营经验整理
// 版本: 2.0 (2026-06) - 全面扩充版，共138条

// 风险等级定义
export const RISK_LEVELS = {
  1: { label: '提示/Info', icon: 'ℹ️', color: 'blue', description: '建议优化，暂无直接风险' },
  2: { label: '注意/Caution', icon: '⚠️', color: 'yellow', description: '可能触发审核，需关注' },
  3: { label: '警告/Warning', icon: '⚡', color: 'orange', description: '较高风险，可能导致listing下架' },
  4: { label: '严重/Severe', icon: '🚫', color: 'red', description: '高风险，可能导致ASIN封禁或账号警告' },
  5: { label: '致命/Fatal', icon: '☠️', color: 'red', description: '极高风险，可能导致账号冻结、法律诉讼或巨额罚款' }
};

// 词库分类
export const WORD_CATEGORIES = {
  MAT: { label: '材质成分', icon: 'fa-shirt', color: 'purple', description: '纺织品标签、材质声明相关' },
  CMP: { label: '合规声明', icon: 'fa-certificate', color: 'amber', description: '认证、合规、保修相关声明' },
  ENV: { label: '环保声明', icon: 'fa-leaf', color: 'green', description: '环保、可持续、绿色声明' },
  MED: { label: '医疗健康', icon: 'fa-heart-pulse', color: 'red', description: '医疗功效、健康声明' },
  ELE: { label: '电子产品', icon: 'fa-bolt', color: 'blue', description: '电子设备、无线通信、电气安全' },
  TOY: { label: '母婴玩具', icon: 'fa-baby', color: 'pink', description: '玩具安全、母婴产品' },
  FOD: { label: '食品接触', icon: 'fa-utensils', color: 'orange', description: '食品接触材料、厨房用品' },
  MKT: { label: '营销话术', icon: 'fa-bullhorn', color: 'indigo', description: '夸大宣传、误导性营销用语' },
  GEO: { label: '地理标识', icon: 'fa-map-marker', color: 'teal', description: '原产地、地理标识保护' },
  IPR: { label: '知识产权', icon: 'fa-copyright', color: 'slate', description: '商标、专利、版权侵权' },
  COS: { label: '化妆品', icon: 'fa-spray-can', color: 'rose', description: '化妆品、个人护理品合规' },
  CHM: { label: '化学安全', icon: 'fa-flask', color: 'lime', description: 'REACH、化学物质限制' },
  PRC: { label: '价格促销', icon: 'fa-tag', color: 'cyan', description: '价格标注、促销合规' },
  DPR: { label: '数据隐私', icon: 'fa-shield', color: 'gray', description: 'GDPR、数据保护相关' },
  PKG: { label: '包装标识', icon: 'fa-box', color: 'brown', description: '包装法、EPR、标签要求' },
  PET: { label: '宠物用品', icon: 'fa-paw', color: 'emerald', description: '宠物食品、用品合规' },
  SPT: { label: '运动户外', icon: 'fa-dumbbell', color: 'sky', description: '运动器材、户外装备安全' },
  AUT: { label: '汽车配件', icon: 'fa-car', color: 'stone', description: '汽车配件、车载设备合规' },
  LGT: { label: '照明灯具', icon: 'fa-lightbulb', color: 'yellow', description: '灯具、LED、能效标识' },
  FUR: { label: '家具家居', icon: 'fa-couch', color: 'warmGray', description: '家具安全、家居产品合规' }
};

// 欧洲站点
export const EU_SITES = ['DE', 'FR', 'IT', 'ES', 'NL', 'SE', 'PL', 'BE', 'GB'];

// 高危词库数据库
export const RESTRICTED_WORDS_DATABASE = [

  // ============================================================
  // === MAT 材质成分 (Textiles & Materials) ===
  // ============================================================
  {
    id: 'MAT-001',
    keyword: 'Bamboo',
    localizedKeywords: { DE: 'Bambus', FR: 'Bambou', IT: 'Bambù', ES: 'Bambú' },
    variants: ['Bambus', 'Bambou', 'Bambù', 'Bambú', 'Bamboo fiber', 'Bambusfaser'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'GB'],
    commonProducts: ['内裤', '袜子', '床品', '毛巾', 'T恤'],
    riskDescription: '德国严查！竹纤维本质是粘胶纤维(Viscose)，标"Bamboo"属于消费欺诈。FTC已多次开罚，EU同步跟进。',
    legalBasis: 'Textile Regulation (EU) 1007/2011',
    alternatives: ['Viscose (from Bamboo)', 'Rayon from Bamboo', 'Regenerated cellulose fiber'],
    tips: 'DE站必须写 "Viskose aus Bambuszellstoff"，绝对不能标"Bamboo"作为纤维名称'
  },
  {
    id: 'MAT-002',
    keyword: 'Lycra',
    localizedKeywords: { DE: 'Elastan', FR: 'Élasthanne', IT: 'Elastan', ES: 'Elastano' },
    variants: ['Elastan', 'Élasthanne', 'Elastam', 'Elastano', 'Spandex'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['瑜伽裤', '泳衣', '运动内衣', '紧身衣'],
    riskDescription: 'Lycra是英威达(INVISTA)的注册商标，Spandex是美式通用名。欧洲法规只接受"Elastane"作为通用纤维名称。',
    legalBasis: 'EU 1007/2011 Annex I',
    alternatives: ['Elastane', 'Elasthan (DE)', 'Élasthanne (FR)'],
    tips: '欧洲站慎用Spandex，首选Elastane。标注格式应为：80% Polyester, 20% Elastane'
  },
  {
    id: 'MAT-003',
    keyword: 'PU Leather',
    localizedKeywords: { DE: 'Kunstleder', FR: 'Similicuir', IT: 'Ecopelle', ES: 'Cuero sintético' },
    variants: ['Kunstleder', 'Cuir synthétique', 'Faux leather', 'Ecopelle', 'Vegan leather', 'PU-Leder'],
    category: 'MAT',
    subCategory: '材质声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['皮包', '沙发', '钱包', '手表带', '鞋子'],
    riskDescription: '易误导消费者认为是真皮。DE站严禁将"Leder"与合成材料混用。标题中出现单独的"Leather"而产品实际是PU，构成消费欺诈。',
    legalBasis: 'UCPD 2005/29/EC, German UWG',
    alternatives: ['Synthetic Leather', 'Faux Leather', 'Kunstleder (DE)', 'Imitation leather'],
    tips: 'Listing中避免出现单独的"Leather"。"Vegan Leather"在德国也有争议'
  },
  {
    id: 'MAT-004',
    keyword: 'Alcantara',
    localizedKeywords: {},
    variants: ['Alcantara-like', 'Alcantara style'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'GB'],
    commonProducts: ['汽车内饰', '手机壳', '沙发套', '方向盘套'],
    riskDescription: 'Alcantara是意大利Alcantara S.p.A.的注册商标，维权极为积极。非授权产品使用即构成侵权。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Suede-like fabric', 'Microfiber suede', 'Ultrasuede-texture'],
    tips: '极高危商标词。即使是"Alcantara-like"也不安全'
  },
  {
    id: 'MAT-005',
    keyword: 'Pashmina',
    localizedKeywords: { DE: 'Kaschmir', FR: 'Cachemire', IT: 'Cashmere', ES: 'Cachemira' },
    variants: ['Cashmere', 'Kaschmir', 'Cachemire', 'Kashmir', 'Cachemira'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR', 'IT'],
    commonProducts: ['围巾', '披肩', '毛衣', '大衣'],
    riskDescription: '必须是100%山羊绒(Capra Hircus)才能标注Cashmere/Pashmina。混纺须标百分比。一旦检测不含羊绒，直接面临欺诈指控。',
    legalBasis: 'EU 1007/2011, Textile Fibre Names',
    alternatives: ['Soft synthetic scarf', 'Cashmere-feel (极谨慎)', 'Cashmere blend XX%'],
    tips: '一旦检测不含羊绒，直接封号。即使含羊绒也必须标明准确百分比'
  },
  {
    id: 'MAT-006',
    keyword: 'Silk',
    localizedKeywords: { DE: 'Seide', FR: 'Soie', IT: 'Seta', ES: 'Seda' },
    variants: ['Seide', 'Soie', 'Seta', 'Seda', 'Silky', 'Satin silk'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT', 'GB'],
    commonProducts: ['睡衣', '枕套', '围巾', '领带', '眼罩'],
    riskDescription: 'Silk/Seide只能用于100%蚕丝产品。聚酯面料不能标"Silk"或"Silky"。标题写"Silk Pillowcase"但实际是Satin(聚酯)是高频违规。',
    legalBasis: 'EU 1007/2011 Annex I (fibre No.1: Silk)',
    alternatives: ['Satin (如果是聚酯)', 'Silk-like satin', 'Satin finish'],
    tips: '"Silky satin"在德国有风险。正确做法：Satin Pillowcase (100% Polyester)'
  },
  {
    id: 'MAT-007',
    keyword: 'Modal',
    localizedKeywords: {},
    variants: ['Lenzing Modal', 'MicroModal'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 2,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['内衣', 'T恤', '睡衣'],
    riskDescription: 'Modal是EU 1007/2011认可的纤维名。但"MicroModal"是Lenzing商标。需确认成分标注准确性。',
    legalBasis: 'EU 1007/2011',
    alternatives: ['Modal fibers'],
    tips: '建议写明百分比：95% Modal, 5% Elastane。不要用MicroModal除非有Lenzing授权'
  },
  {
    id: 'MAT-008',
    keyword: 'Chiffon',
    localizedKeywords: {},
    variants: ['Georgette', 'Organza'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 2,
    affectedSites: ['GB', 'DE', 'FR'],
    commonProducts: ['连衣裙', '上衣', '丝巾'],
    riskDescription: 'Chiffon/Georgette/Organza是织造工艺描述而非纤维成分。欧盟要求标注纤维成分而非织造名称。',
    legalBasis: 'EU 1007/2011 Article 9',
    alternatives: ['100% Polyester (Chiffon weave)', 'Polyester Chiffon'],
    tips: '不能只写Chiffon作为材质成分。正确格式：Material: 100% Polyester; Fabric: Chiffon'
  },
  {
    id: 'MAT-009',
    keyword: 'Velcro',
    localizedKeywords: { DE: 'Klettverschluss', FR: 'Fermeture auto-agrippante' },
    variants: ['Klettverschluss', 'Scratch', 'Klittenband'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'NL'],
    commonProducts: ['鞋子', '收纳带', '线缆管理', '背包'],
    riskDescription: 'Velcro是Velcro Companies的注册商标，该公司积极维权（甚至拍过维权宣传视频）。非授权产品禁用。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Hook and loop fastener', 'Hook-and-loop closure', 'Klettverschluss (DE)'],
    tips: '极易侵权，务必用Hook and Loop。Velcro公司有专门团队扫描亚马逊'
  },
  {
    id: 'MAT-010',
    keyword: 'Gore-Tex',
    localizedKeywords: {},
    variants: ['Goretex', 'Gore Tex'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'GB', 'FR', 'IT', 'ES'],
    commonProducts: ['冲锋衣', '登山鞋', '手套', '帐篷'],
    riskDescription: '知名防水透气面料商标，W. L. Gore & Associates维权极为积极。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Waterproof breathable fabric', 'Waterproof membrane'],
    tips: '禁用Gore-Tex及任何变体。"Gore-Tex-like"也不行'
  },
  {
    id: 'MAT-011',
    keyword: 'Linen',
    localizedKeywords: { DE: 'Leinen', FR: 'Lin', IT: 'Lino', ES: 'Lino' },
    variants: ['Leinen', 'Lin', 'Lino', 'Flax'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['桌布', '床单', '衬衫', '窗帘'],
    riskDescription: 'Linen(亚麻)是特定纤维名称，只能用于亚麻纤维产品。棉/涤产品标"Linen look"在部分国家有争议。',
    legalBasis: 'EU 1007/2011 Annex I (fibre No.7: Flax/Linen)',
    alternatives: ['Linen-look (需注明实际成分)', 'Cotton linen blend (标明百分比)'],
    tips: '"Linen texture"这种模糊表述在DE站有风险'
  },
  {
    id: 'MAT-012',
    keyword: 'Merino',
    localizedKeywords: { DE: 'Merinowolle', FR: 'Laine mérinos' },
    variants: ['Merino wool', 'Merinowolle'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 3,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['袜子', '内衣', '运动衫'],
    riskDescription: '需确保确实是Merino羊品种的羊毛。普通羊毛不能标Merino，且需标明百分比。',
    legalBasis: 'EU 1007/2011',
    alternatives: ['Wool', 'Fine wool'],
    tips: '混纺产品：80% Merino Wool, 20% Polyamide'
  },
  {
    id: 'MAT-013',
    keyword: 'Tencel',
    localizedKeywords: {},
    variants: ['TENCEL™'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['床品', '内衣', 'T恤'],
    riskDescription: 'TENCEL™是Lenzing AG的注册商标。非Lenzing纤维不得使用此名称。通用名应使用Lyocell。',
    legalBasis: 'EU Trademark Regulation / EU 1007/2011',
    alternatives: ['Lyocell', 'Lyocell (Eucalyptus fiber)'],
    tips: '如确实使用Lenzing原料，需按其品牌指南标注：TENCEL™ Lyocell'
  },
  {
    id: 'MAT-014',
    keyword: 'Neoprene',
    localizedKeywords: { DE: 'Neopren' },
    variants: ['Neopren', 'Chloroprene rubber'],
    category: 'MAT',
    subCategory: '材质声明',
    riskLevel: 3,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['潜水衣', '笔记本电脑包', '护膝'],
    riskDescription: 'Neoprene曾是DuPont商标（已过期），现为通用名。但REACH对氯丁橡胶中的多环芳烃(PAH)有限制。',
    legalBasis: 'REACH Annex XVII Entry 50',
    alternatives: ['Synthetic rubber sleeve', 'CR foam'],
    tips: '注意PAH含量合规'
  },
  {
    id: 'MAT-015',
    keyword: 'Teflon',
    localizedKeywords: {},
    variants: ['PTFE', 'Non-stick coating'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'GB'],
    commonProducts: ['锅', '烤盘', '电饭煲内胆'],
    riskDescription: 'Teflon是Chemours(原DuPont)的注册商标。此外PFAS限制法规正在收紧。',
    legalBasis: 'EU Trademark / PFAS Restriction Proposal',
    alternatives: ['Non-stick coating', 'PTFE-free coating', 'Ceramic coating'],
    tips: 'PFAS"永久化学品"是欧洲热门环保议题，有全面禁令趋势'
  },
  {
    id: 'MAT-016',
    keyword: 'Cordura',
    localizedKeywords: {},
    variants: ['CORDURA®'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['背包', '工装裤', '行李箱'],
    riskDescription: 'CORDURA®是INVISTA的注册商标，非授权产品禁用。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Heavy-duty nylon', 'Ballistic nylon', 'Ripstop nylon'],
    tips: '需要INVISTA的品牌授权才能使用'
  },
  {
    id: 'MAT-017',
    keyword: 'Polartec',
    localizedKeywords: {},
    variants: ['POLARTEC®'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['抓绒衣', '手套', '帽子'],
    riskDescription: 'Polartec是Milliken & Company的注册商标。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Fleece', 'Polar fleece', 'Microfleece'],
    tips: '用Fleece或Polar Fleece替代'
  },
  {
    id: 'MAT-018',
    keyword: 'Velour',
    localizedKeywords: { DE: 'Velours', FR: 'Velours' },
    variants: ['Velvet', 'Samt'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 2,
    affectedSites: ['DE'],
    commonProducts: ['沙发', '窗帘', '连衣裙'],
    riskDescription: '织造工艺名称，需同时标明纤维成分。如"100% Polyester Velvet"。',
    legalBasis: 'EU 1007/2011',
    alternatives: ['Polyester velvet', 'Cotton velour'],
    tips: '单独标"Velvet"不符合纺织标签要求'
  },
  {
    id: 'MAT-019',
    keyword: 'Hemp',
    localizedKeywords: { DE: 'Hanf', FR: 'Chanvre', IT: 'Canapa', ES: 'Cáñamo' },
    variants: ['Hanf', 'Chanvre', 'Canapa', 'Cáñamo'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['背包', '鞋子', '服装'],
    riskDescription: '汉麻是合法纤维，但关键词可能触发大麻相关审核(尤其是带CBD/Cannabis的关联词)。需确认THC含量<0.2%(EU)/0.3%。',
    legalBasis: 'EU 1007/2011 / Novel Food Regulation',
    alternatives: ['Natural fiber bag', 'Plant-based fiber'],
    tips: '纯纤维用途可以写Hemp，但不要与CBD/Cannabis关联'
  },
  {
    id: 'MAT-020',
    keyword: 'Down',
    localizedKeywords: { DE: 'Daunen', FR: 'Duvet', IT: 'Piumino', ES: 'Plumón' },
    variants: ['Daunen', 'Duvet', 'Piumino', 'Goose down', 'Duck down', 'Gänsedaunen'],
    category: 'MAT',
    subCategory: '填充物',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['羽绒被', '羽绒服', '枕头'],
    riskDescription: '必须标明Down/Feather比例和来源(鹅/鸭)。DE站对蓬松度(Fill Power)标注有严格要求。需标明是否负责任采购(RDS认证)。',
    legalBasis: 'EN 12934 / Textile Regulation',
    alternatives: ['Synthetic down alternative', 'Hollow fiber filling'],
    tips: '格式：90% White Goose Down, 10% Feather, 800 Fill Power'
  },
  {
    id: 'MAT-021',
    keyword: 'Organic Cotton',
    localizedKeywords: { DE: 'Bio-Baumwolle', FR: 'Coton biologique' },
    variants: ['Bio-Baumwolle', 'Coton bio', 'GOTS certified cotton'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB', 'NL'],
    commonProducts: ['婴儿服', 'T恤', '毛巾', '床品'],
    riskDescription: '标注"Organic"需GOTS或OCS认证。无证使用"Organic Cotton"是虚假广告。EU Organic Regulation严格要求认证追溯。',
    legalBasis: 'EU Organic Regulation 2018/848 / GOTS',
    alternatives: ['Natural cotton', 'Sustainably sourced cotton'],
    tips: '必须持有有效GOTS证书且注明证书编号'
  },
  {
    id: 'MAT-022',
    keyword: 'Stainless Steel 316',
    localizedKeywords: { DE: 'Edelstahl 316', FR: 'Acier inoxydable 316' },
    variants: ['316L', 'Surgical steel', 'Medical grade steel'],
    category: 'MAT',
    subCategory: '金属材质',
    riskLevel: 3,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['首饰', '水壶', '餐具', '手表'],
    riskDescription: '标注具体钢号需确保材质证书支持。"Surgical steel"暗示医疗级别，可能触发MDR审核。REACH对镍释放有严格限制。',
    legalBasis: 'REACH Annex XVII Entry 27 (Nickel)',
    alternatives: ['Stainless steel (不标具体型号)', 'Hypoallergenic steel'],
    tips: '首饰类Nickel release <0.5μg/cm²/week'
  },
  {
    id: 'MAT-023',
    keyword: 'Genuine Leather',
    localizedKeywords: { DE: 'Echtleder', FR: 'Cuir véritable', IT: 'Vera pelle', ES: 'Cuero genuino' },
    variants: ['Echtleder', 'Cuir véritable', 'Vera pelle', 'Real leather', 'Full grain leather'],
    category: 'MAT',
    subCategory: '材质声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['皮带', '钱包', '鞋子', '手提包'],
    riskDescription: '标注真皮需确保产品确实使用动物皮革。"Genuine Leather"在行业中实际是较低等级的皮革。DE站对皮革标注特别严格。',
    legalBasis: 'UCPD / German Leather Marking Regulation',
    alternatives: ['如实标注皮革等级: Full grain / Top grain / Split leather'],
    tips: '标"Genuine Leather"需确保REACH铬VI含量<3mg/kg'
  },
  {
    id: 'MAT-024',
    keyword: 'Angora',
    localizedKeywords: { DE: 'Angorawolle', FR: 'Angora' },
    variants: ['Angora wool', 'Angorawolle', 'Rabbit hair'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'NL', 'SE'],
    commonProducts: ['毛衣', '围巾', '帽子'],
    riskDescription: '安哥拉兔毛因动物福利问题在欧洲高度敏感。多家欧洲零售商已禁售。亚马逊可能随时调整政策。',
    legalBasis: 'EU Animal Welfare regulations / Retailer policies',
    alternatives: ['Mohair (安哥拉山羊毛，不同)', 'Soft acrylic blend'],
    tips: '即使合法，也面临消费者投诉和品牌风险'
  },
  {
    id: 'MAT-025',
    keyword: 'Fur',
    localizedKeywords: { DE: 'Pelz', FR: 'Fourrure', IT: 'Pelliccia', ES: 'Piel' },
    variants: ['Pelz', 'Fourrure', 'Real fur', 'Echtpelz', 'Mink', 'Fox fur'],
    category: 'MAT',
    subCategory: '动物制品',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'NL', 'BE', 'GB'],
    commonProducts: ['大衣领子', '帽子', '钥匙链'],
    riskDescription: '多个欧洲国家已禁止养殖皮草(NL、BE、英国等)。EU正推进全面禁令。Faux fur标注不当也有风险。',
    legalBasis: 'EU Fur Farming bans / Textile Regulation',
    alternatives: ['Faux fur', 'Synthetic fur', 'Kunstpelz (DE)'],
    tips: 'Faux fur也需标明成分(如100% Polyester)。不能只写"Fur"模糊处理'
  },
  {
    id: 'MAT-026',
    keyword: 'Kevlar',
    localizedKeywords: {},
    variants: ['KEVLAR®', 'Aramid'],
    category: 'MAT',
    subCategory: '商标材质',
    riskLevel: 5,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['手机壳', '手套', '摩托车配件'],
    riskDescription: 'KEVLAR®是DuPont(现Dupont de Nemours)的注册商标。通用名称应使用"Aramid fiber"。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Aramid fiber', 'Para-aramid', 'High-strength synthetic fiber'],
    tips: '用Aramid替代Kevlar'
  },

  // ============================================================
  // === CMP 合规声明 (Compliance) ===
  // ============================================================
  {
    id: 'CMP-001',
    keyword: 'CE Certified',
    localizedKeywords: { DE: 'CE-zertifiziert', FR: 'Certifié CE', IT: 'Certificato CE', ES: 'Certificado CE' },
    variants: ['CE Approved', 'CE geprüft', 'CE Mark', 'CE Marked', 'CE-Kennzeichnung'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'GB'],
    commonProducts: ['电子产品', '玩具', '个人防护装备', '医疗器械'],
    riskDescription: 'CE标志是法律强制要求，不是质量认证。宣传"CE Certified"暗示其他合规产品不安全，属于不正当竞争。且CE是自我声明，不是认证。',
    legalBasis: 'UCPD 2005/29/EC, Regulation 765/2008',
    alternatives: ['不宣传CE', '产品图片中自然展示CE标志即可'],
    tips: '图片中可展示真实存在的CE标，但文案中不应将其作为卖点。GB站UKCA/CE口径按当前政府指南和品类规则复核'
  },
  {
    id: 'CMP-002',
    keyword: 'FDA Approved',
    localizedKeywords: {},
    variants: ['FDA Certified', 'FDA Cleared', 'FDA Registered', 'FDA合格'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'IT', 'ES'],
    commonProducts: ['厨具', '美容仪', '保健品', '硅胶制品'],
    riskDescription: 'FDA是美国机构，在欧洲无管辖权。宣传FDA认证既无意义又构成误导。且"FDA Approved"本身在美国都常被误用（FDA注册≠FDA批准）。',
    legalBasis: 'UCPD 2005/29/EC, Misleading Advertising Directive',
    alternatives: ['LFGB compliant (DE)', 'Food-safe (EU 1935/2004)', 'DGCCRF tested (FR)'],
    tips: '欧洲认LFGB(DE), DGCCRF(FR)。删除所有FDA相关声明'
  },
  {
    id: 'CMP-003',
    keyword: 'RoHS Compliant',
    localizedKeywords: { DE: 'RoHS-konform', FR: 'Conforme RoHS' },
    variants: ['RoHS certified', 'RoHS free'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['电子产品', 'LED灯', '充电器'],
    riskDescription: 'RoHS是电子产品在欧洲销售的法定义务，不能作为独特卖点宣传。就像"本产品合法"一样不应作为广告。',
    legalBasis: 'UCPD 2005/29/EC, RoHS Directive 2011/65/EU',
    alternatives: ['删除RoHS相关营销文案'],
    tips: '默认合规即可，不要拿法定义务做卖点'
  },
  {
    id: 'CMP-004',
    keyword: 'TÜV Certified',
    localizedKeywords: { DE: 'TÜV geprüft', FR: 'Certifié TÜV' },
    variants: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV Nord', 'TÜV tested', 'TÜV-geprüft'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 5,
    affectedSites: ['DE'],
    commonProducts: ['汽配', '电器', '家具', '充电器'],
    riskDescription: 'TÜV是德国技术监督协会的注册商标。必须持有有效TÜV证书才能使用，且需在Listing中注明证书编号。虚假使用TÜV标志是刑事犯罪。',
    legalBasis: 'German Trademark Law / Certification Marks',
    alternatives: ['Safety tested', 'Independently tested'],
    tips: '德国消费者极度信赖TÜV，但也极爱举报造假。伪造TÜV标志可面临刑事起诉'
  },
  {
    id: 'CMP-005',
    keyword: 'GS Mark',
    localizedKeywords: { DE: 'GS-Zeichen' },
    variants: ['Geprüfte Sicherheit', 'GS certified', 'GS geprüft'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 4,
    affectedSites: ['DE'],
    commonProducts: ['工具', '家电', '充电器', '小家电'],
    riskDescription: 'GS(Geprüfte Sicherheit)是德国产品安全法下的自愿认证，但乱标会被巨额罚款。GS标志需由认可机构(如TÜV)颁发。',
    legalBasis: 'ProdSG (German Product Safety Act) §21',
    alternatives: ['删除GS相关描述', 'Tested for safety'],
    tips: '无证严禁提及GS。取得GS认证需要工厂审核'
  },
  {
    id: 'CMP-006',
    keyword: 'Warranty',
    localizedKeywords: { DE: 'Garantie', FR: 'Garantie', IT: 'Garanzia', ES: 'Garantía' },
    variants: ['Guarantee', 'Garantie', 'Gewährleistung', 'Lifetime warranty'],
    category: 'CMP',
    subCategory: '售后条款',
    riskLevel: 4,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['所有产品'],
    riskDescription: '德国法律严格区分"Garantie"(商业保修)和"Gewährleistung"(法定质保)。提"Garantie"必须附带完整保修条款(Garantiebedingungen)，包括时长、范围、维修方式等。缺失条款即违法。',
    legalBasis: 'German BGB §443, §479; Consumer Rights Directive',
    alternatives: ['24-month customer support', 'Quality promise', 'Satisfaction guarantee (需条款)'],
    tips: '"Lifetime Warranty"在德国几乎不可能合规执行，极度危险。建议用"zufriedenheitsversprechen"(满意承诺)'
  },
  {
    id: 'CMP-007',
    keyword: 'Free Shipping',
    localizedKeywords: { DE: 'Versandkostenfrei', FR: 'Livraison gratuite' },
    variants: ['Kostenloser Versand', 'Free delivery'],
    category: 'CMP',
    subCategory: '营销声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['FBA产品'],
    riskDescription: 'Prime产品本身包邮，强调"Free Shipping"属于宣传自明事实(Self-evident claim)，可能构成不正当竞争。',
    legalBasis: 'UCPD 2005/29/EC, German UWG',
    alternatives: ['Fast delivery', 'Schnelle Lieferung'],
    tips: 'Prime商品别特意强调包邮，FBM商品可以写'
  },
  {
    id: 'CMP-008',
    keyword: 'UKCA',
    localizedKeywords: {},
    variants: ['UK Conformity Assessed'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 4,
    affectedSites: ['GB'],
    commonProducts: ['电子产品', '玩具', '化妆品'],
    riskDescription: 'GB市场的UKCA与CE认可口径需按当前英国政府指南和具体品类法规复核。在GB站宣传CE/UKCA时必须有真实标签和合规资料支撑。',
    legalBasis: 'UK Product Safety Regulations',
    alternatives: ['确认当前GB市场接受的标志要求'],
    tips: '关注英国政府指南和品类规则变化，CE/UKCA口径不得按固定年份硬套'
  },
  {
    id: 'CMP-009',
    keyword: 'Made in Germany',
    localizedKeywords: { DE: 'Hergestellt in Deutschland', FR: 'Fabriqué en Allemagne' },
    variants: ['German quality', 'Deutsche Qualität', 'German engineering'],
    category: 'CMP',
    subCategory: '产地声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['工具', '厨具', '汽配'],
    riskDescription: '标注"Made in Germany"需产品主要生产步骤在德国完成。进口产品贴"German Quality"属于误导性广告。',
    legalBasis: 'German UWG (Unfair Competition Act), UCPD',
    alternatives: ['Designed in Germany (如确实是)', 'German brand'],
    tips: '中国制造贴"German Quality"是高频违规点'
  },
  {
    id: 'CMP-010',
    keyword: 'Tested',
    localizedKeywords: { DE: 'Getestet', FR: 'Testé' },
    variants: ['Lab tested', 'Clinically tested', 'Dermatologically tested'],
    category: 'CMP',
    subCategory: '测试声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['化妆品', '保健品', '电子产品'],
    riskDescription: '声称"经测试"需有实际测试报告。"Clinically tested"需有临床试验数据。"Dermatologically tested"需有皮肤科医生参与的测试。',
    legalBasis: 'UCPD, Cosmetic Regulation (EC) 1223/2009',
    alternatives: ['Quality checked (如有内部QC流程)'],
    tips: '保留所有测试报告，随时可能被要求提供'
  },
  {
    id: 'CMP-011',
    keyword: 'Patent',
    localizedKeywords: { DE: 'Patent', FR: 'Brevet' },
    variants: ['Patented', 'Patent pending', 'Patentiert'],
    category: 'CMP',
    subCategory: '知识产权声明',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['创新产品'],
    riskDescription: '声称"Patented"需持有有效欧洲专利(EP)或国家专利。虚假专利声明在德国是严重违法行为。专利过期后继续标注也违法。',
    legalBasis: 'European Patent Convention, German PatG',
    alternatives: ['Innovative design', 'Unique technology'],
    tips: '如有专利，建议标注专利号：EP XXXXXXX'
  },
  {
    id: 'CMP-012',
    keyword: 'Award Winning',
    localizedKeywords: { DE: 'Preisgekrönt', FR: 'Primé' },
    variants: ['Best seller', 'Nr. 1', 'Number one', '#1', 'Bestseller'],
    category: 'CMP',
    subCategory: '营销声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['所有产品'],
    riskDescription: '"Award winning"需标明具体奖项和年份。"Nr.1"/"Bestseller"需有市场数据支持。"Amazon Bestseller"需注意亚马逊政策限制。',
    legalBasis: 'UCPD, German UWG §5',
    alternatives: ['Popular choice', 'Customer favorite'],
    tips: '声称"Nr.1"必须注明数据来源和时间范围'
  },
  {
    id: 'CMP-013',
    keyword: 'Hypoallergenic',
    localizedKeywords: { DE: 'Hypoallergen', FR: 'Hypoallergénique' },
    variants: ['Anti-allergic', 'Allergen-free', 'Allergikergeeignet'],
    category: 'CMP',
    subCategory: '健康声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['首饰', '床品', '化妆品', '婴儿用品'],
    riskDescription: '"Hypoallergenic"意为"较少过敏风险"，但无法律定义和统一标准。某些国家对此声明要求有测试支持。',
    legalBasis: 'Cosmetic Regulation (EC) 1223/2009, UCPD',
    alternatives: ['Suitable for sensitive skin (需测试支持)', 'Nickel-free (如实际无镍)'],
    tips: '不要绝对化，"Anti-allergic"比"Hypoallergenic"风险更高'
  },
  {
    id: 'CMP-014',
    keyword: 'OEKO-TEX',
    localizedKeywords: {},
    variants: ['Oeko-Tex Standard 100', 'OEKO-TEX certified', 'Öko-Tex'],
    category: 'CMP',
    subCategory: '认证声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['纺织品', '床品', '婴儿服'],
    riskDescription: 'OEKO-TEX®是注册商标。需持有有效证书且可在OEKO-TEX官网验证。证书有效期一年需续期。过期证书继续使用即侵权。',
    legalBasis: 'EU Trademark Regulation',
    alternatives: ['Tested for harmful substances'],
    tips: '如有证书，注明证书编号且确保在有效期内'
  },
  {
    id: 'CMP-015',
    keyword: 'Money Back',
    localizedKeywords: { DE: 'Geld zurück', FR: 'Remboursement' },
    variants: ['Money-back guarantee', 'Geld-zurück-Garantie', '100% refund'],
    category: 'CMP',
    subCategory: '售后条款',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['所有产品'],
    riskDescription: '欧盟消费者已有14天无理由退货权(Distance Selling Directive)。宣传"Money Back"作为特殊卖点属宣传法定权利。如超出法定权利需明确条款。',
    legalBasis: 'Consumer Rights Directive 2011/83/EU, German BGB',
    alternatives: ['Extended return policy (30 days)', 'Satisfaction promise'],
    tips: '14天退货权是法定的，不应作为独特卖点宣传'
  },

  // ============================================================
  // === ENV 环保声明 (Environmental) ===
  // ============================================================
  {
    id: 'ENV-001',
    keyword: 'Eco-Friendly',
    localizedKeywords: { DE: 'Umweltfreundlich', FR: 'Écologique', IT: 'Ecologico', ES: 'Ecológico' },
    variants: ['Green', 'Nature friendly', 'Environmentally friendly', 'Eco', 'Nachhaltig'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB', 'NL', 'SE'],
    commonProducts: ['全品类'],
    riskDescription: '欧盟绿色声明指令(Green Claims Directive, 预计2026年生效)严打模糊环保声明(Greenwashing)。无具体证据的"Eco-friendly"将被视为欺骗性商业行为。',
    legalBasis: 'Green Claims Directive (Proposal), UCPD 2005/29/EC',
    alternatives: ['Made of 100% recycled PET', 'Energy class A', 'FSC certified packaging'],
    tips: '必须具体且可验证：哪个方面环保？基于什么标准/数据？'
  },
  {
    id: 'ENV-002',
    keyword: 'Biodegradable',
    localizedKeywords: { DE: 'Biologisch abbaubar', FR: 'Biodégradable', IT: 'Biodegradabile', ES: 'Biodegradable' },
    variants: ['Degradable', 'Compostable', 'Abbaubar'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'NL'],
    commonProducts: ['垃圾袋', '餐具', '包装材料', '手机壳'],
    riskDescription: '必须符合EN 13432标准并持有OK Compost或类似认证。法国已禁止oxo-degradable(氧化降解)塑料。"Biodegradable"不等于"Compostable"。',
    legalBasis: 'Single-Use Plastics Directive 2019/904, EN 13432',
    alternatives: ['Compostable (EN 13432 certified)', 'Made from renewable materials'],
    tips: 'Oxo-degradable在欧洲是彻底违禁。标"Biodegradable"的产品在环境中可能实际上不降解'
  },
  {
    id: 'ENV-003',
    keyword: 'Carbon Neutral',
    localizedKeywords: { DE: 'Klimaneutral', FR: 'Neutre en carbone' },
    variants: ['CO2 Neutral', 'Climate neutral', 'Net zero', 'Klimaneutral'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'NL'],
    commonProducts: ['所有产品'],
    riskDescription: '德国法院(BGH)已裁定"Klimaneutral"声明必须附带具体解释和可验证的证据。仅购买碳补偿(carbon offsets)不够。需提供LCA(生命周期评估)数据。',
    legalBasis: 'German UWG, Green Claims Directive (Proposal)',
    alternatives: ['Reduced carbon footprint (with data)', 'X% lower CO2 compared to...'],
    tips: '德国法院2023年标志性判决：仅靠碳补偿不能宣称"Klimaneutral"'
  },
  {
    id: 'ENV-004',
    keyword: 'BPA Free',
    localizedKeywords: { DE: 'BPA-frei', FR: 'Sans BPA', IT: 'Senza BPA' },
    variants: ['Bisphenol A free', 'BPA-frei', 'Sans BPA'],
    category: 'ENV',
    subCategory: '化学声明',
    riskLevel: 3,
    affectedSites: ['FR', 'BE'],
    commonProducts: ['奶瓶', '食品容器', '水瓶', '保鲜盒'],
    riskDescription: '法国法律已全面禁止BPA用于食品接触材料(2015年起)。在法国标"Sans BPA"反而暗示别的产品含BPA，构成误导(宣传法定义务)。',
    legalBasis: 'Loi n° 2010-729, Loi n° 2012-1442 (France)',
    alternatives: ['Food grade material', 'Safe for food contact'],
    tips: '仅法国/比利时站：不要强调"Sans BPA"。其他站点可以标注'
  },
  {
    id: 'ENV-005',
    keyword: 'Sustainable',
    localizedKeywords: { DE: 'Nachhaltig', FR: 'Durable', IT: 'Sostenibile', ES: 'Sostenible' },
    variants: ['Nachhaltig', 'Sustainability', 'Sustainably sourced'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'NL', 'SE', 'GB'],
    commonProducts: ['全品类'],
    riskDescription: '与"Eco-friendly"同属模糊环保声明。Green Claims Directive要求所有环保声明基于科学证据和PEF(Product Environmental Footprint)方法。',
    legalBasis: 'Green Claims Directive (Proposal), UCPD',
    alternatives: ['Made from X% recycled material', 'FSC certified'],
    tips: '"Sustainable"太笼统。具体说明哪个方面可持续'
  },
  {
    id: 'ENV-006',
    keyword: 'Recyclable',
    localizedKeywords: { DE: 'Recycelbar', FR: 'Recyclable', IT: 'Riciclabile' },
    variants: ['Recycelbar', '100% recyclable', 'Fully recyclable'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['包装', '水瓶', '购物袋'],
    riskDescription: '"Recyclable"需考虑当地实际回收基础设施。理论上可回收但实际上不被回收的材料不应标注"Recyclable"。',
    legalBasis: 'Green Claims Directive, Packaging and Packaging Waste Regulation',
    alternatives: ['Check local recycling guidelines', 'Made from recycled material'],
    tips: '注明材质以便消费者判断：PP5 recyclable'
  },
  {
    id: 'ENV-007',
    keyword: 'Plastic Free',
    localizedKeywords: { DE: 'Plastikfrei', FR: 'Sans plastique' },
    variants: ['Plastikfrei', 'Zero plastic', 'No plastic'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 3,
    affectedSites: ['DE', 'GB', 'NL'],
    commonProducts: ['包装', '厨房用品', '个人护理'],
    riskDescription: '产品本身无塑料但包装含塑料时，"Plastic Free"声明存在误导风险。需明确范围：产品/包装/整体。',
    legalBasis: 'UCPD, Green Claims Directive',
    alternatives: ['Plastic-free product (packaging may contain recycled plastic)'],
    tips: '确保包括包装、标签、胶带等全链路无塑料'
  },
  {
    id: 'ENV-008',
    keyword: 'Natural',
    localizedKeywords: { DE: 'Natürlich', FR: 'Naturel', IT: 'Naturale', ES: 'Natural' },
    variants: ['Natürlich', 'Naturel', '100% natural', 'All natural', 'Rein natürlich'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['化妆品', '清洁用品', '食品补充剂'],
    riskDescription: '"Natural"没有法律定义(化妆品领域部分国家有)。含有任何合成成分都不应标"100% Natural"。',
    legalBasis: 'UCPD, ISO 16128 (Cosmetics)',
    alternatives: ['Contains natural ingredients', 'Plant-based'],
    tips: '化妆品中可参考ISO 16128计算天然成分比例'
  },
  {
    id: 'ENV-009',
    keyword: 'Vegan',
    localizedKeywords: { DE: 'Vegan', FR: 'Végan' },
    variants: ['Vegan friendly', 'Plant-based', 'Cruelty-free'],
    category: 'ENV',
    subCategory: '环保/伦理声明',
    riskLevel: 2,
    affectedSites: ['DE', 'GB', 'NL'],
    commonProducts: ['化妆品', '食品', '服装', '鞋子'],
    riskDescription: '"Vegan"声明需确保产品不含任何动物来源成分(包括胶水、染料中的动物成分)。"Cruelty-free"指不做动物测试。两者不等价。',
    legalBasis: 'UCPD, Cosmetic Regulation',
    alternatives: ['如实标注', 'V-Label certified (有认证更好)'],
    tips: '建议取得V-Label或The Vegan Society认证以支持声明'
  },
  {
    id: 'ENV-010',
    keyword: 'FSC',
    localizedKeywords: {},
    variants: ['FSC certified', 'FSC-zertifiziert', 'FSC Mix'],
    category: 'ENV',
    subCategory: '环保认证',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB', 'NL'],
    commonProducts: ['纸制品', '木制品', '包装'],
    riskDescription: 'FSC®是Forest Stewardship Council的注册商标。使用FSC标志需持有有效CoC(产销监管链)证书。未授权使用即商标侵权。',
    legalBasis: 'FSC Trademark Policy, EU Deforestation Regulation',
    alternatives: ['Sustainably sourced wood', 'From managed forests'],
    tips: '新EU Deforestation Regulation(2024)要求木材产品提供尽职调查声明'
  },
  {
    id: 'ENV-011',
    keyword: 'Ozone Friendly',
    localizedKeywords: { DE: 'Ozonfreundlich' },
    variants: ['CFC free', 'FCKW-frei'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['喷雾剂', '制冷设备'],
    riskDescription: 'CFC已被蒙特利尔议定书全面禁止。标注"CFC-free"是宣传法定义务。',
    legalBasis: 'UCPD, Montreal Protocol',
    alternatives: ['删除该声明'],
    tips: '不要把遵守法律作为卖点'
  },
  {
    id: 'ENV-012',
    keyword: 'Zero Waste',
    localizedKeywords: { DE: 'Zero Waste', FR: 'Zéro déchet' },
    variants: ['Abfallfrei', 'Waste-free'],
    category: 'ENV',
    subCategory: '环保声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'NL'],
    commonProducts: ['厨房用品', '个人护理', '清洁用品'],
    riskDescription: '绝对性声明极难证实。产品生产、运输过程中不可能完全零废弃。',
    legalBasis: 'Green Claims Directive, UCPD',
    alternatives: ['Minimal packaging', 'Reusable', 'Designed to reduce waste'],
    tips: '避免绝对化声明'
  },
  {
    id: 'ENV-013',
    keyword: 'Energy Saving',
    localizedKeywords: { DE: 'Energiesparend', FR: 'Économe en énergie' },
    variants: ['Low energy', 'Power saving', 'Energy efficient'],
    category: 'ENV',
    subCategory: '能效声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['灯泡', '家电', '充电器'],
    riskDescription: '有能效标签的产品须按EU能效标签规定标注(A到G)。笼统的"Energy saving"不够具体。',
    legalBasis: 'EU Energy Labelling Regulation 2017/1369',
    alternatives: ['Energy class A', 'XX% more efficient than...'],
    tips: '灯具/家电必须展示正确的能效标签'
  },

  // ============================================================
  // === MED 医疗健康 (Medical & Health) ===
  // ============================================================
  {
    id: 'MED-001',
    keyword: 'Cures',
    localizedKeywords: { DE: 'Heilt', FR: 'Guérit', IT: 'Cura', ES: 'Cura' },
    variants: ['Treats', 'Heals', 'Therapy', 'Therapeutic', 'Treatment', 'Heilung', 'Behandlung'],
    category: 'MED',
    subCategory: '医疗功效',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'IT', 'ES'],
    commonProducts: ['保健品', '按摩仪', '护具', '精油', '膏药'],
    riskDescription: '暗示医疗功效的产品可能被归类为药品或医疗器械，需要相应许可证。非药品/医疗器械宣称治愈功效是严重违法行为。',
    legalBasis: 'MDR (EU) 2017/745, Medicinal Products Directive 2001/83/EC',
    alternatives: ['Supports', 'Helps maintain', 'Promotes well-being', 'Contributes to comfort'],
    tips: '普通产品绝对不能写"治愈/治疗"。即使是"may help"也可能越线'
  },
  {
    id: 'MED-002',
    keyword: 'Antibacterial',
    localizedKeywords: { DE: 'Antibakteriell', FR: 'Antibactérien', IT: 'Antibatterico' },
    variants: ['Antimicrobial', 'Antiviral', 'Anti-fungal', 'Bactericidal', 'Keimfrei'],
    category: 'MED',
    subCategory: '生物杀灭',
    riskLevel: 5,
    affectedSites: ['DE', 'GB', 'SE', 'FR', 'NL'],
    commonProducts: ['袜子', '清洁用品', '砧板', '手机壳', '空气净化器'],
    riskDescription: '含杀菌/抗菌活性物质的产品受BPR(生物杀灭剂法规)管辖，需在ECHA注册。产品本身(不仅仅是声明)需要合规。Sweden(SE)执法尤其严格。',
    legalBasis: 'BPR (EU) 528/2012, Biocidal Products Regulation',
    alternatives: ['Hygienic', 'Easy to clean', 'Odor-resistant', 'Quick-drying'],
    tips: '不仅仅是词的问题，产品本身如果含有银离子/纳米银等杀菌成分，需要BPR注册。成本极高'
  },
  {
    id: 'MED-003',
    keyword: 'Whitening',
    localizedKeywords: { DE: 'Aufhellung', FR: 'Blanchiment', IT: 'Sbiancante' },
    variants: ['Bleaching', 'Teeth whitening', 'Zahnaufhellung', 'Skin whitening'],
    category: 'MED',
    subCategory: '化妆品功效',
    riskLevel: 4,
    affectedSites: ['GB', 'DE', 'FR', 'IT'],
    commonProducts: ['牙贴', '牙膏', '护肤品', '美白精华'],
    riskDescription: '牙齿美白：含过氧化氢>0.1%的产品只能由牙科专业人员使用。含>6%的完全禁止。皮肤美白：含汞/对苯二酚的产品禁止销售。',
    legalBasis: 'Cosmetic Regulation (EC) 1223/2009 Annex III',
    alternatives: ['Brightening', 'Radiance-boosting', 'Stain removal (牙膏)'],
    tips: '牙齿美白产品是高退货率+高合规风险品类'
  },
  {
    id: 'MED-004',
    keyword: 'Pain Relief',
    localizedKeywords: { DE: 'Schmerzlinderung', FR: 'Soulagement de la douleur' },
    variants: ['Anti-pain', 'Pain killer', 'Relieves pain', 'Schmerzfrei'],
    category: 'MED',
    subCategory: '医疗功效',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['护具', '枕头', '坐垫', '按摩器', 'TENS设备'],
    riskDescription: '缓解疼痛是医疗功效声明。非医疗器械产品(如枕头、坐垫)不得宣称"Pain Relief"。TENS设备本身可能被归类为Class IIa医疗器械。',
    legalBasis: 'MDR (EU) 2017/745',
    alternatives: ['Comfortable support', 'Ergonomic design', 'Pressure-relieving'],
    tips: '颈椎枕头、腰部坐垫最容易踩此红线。用"comfortable"替代"pain relief"'
  },
  {
    id: 'MED-005',
    keyword: 'Mask',
    localizedKeywords: { DE: 'Maske', FR: 'Masque', IT: 'Maschera' },
    variants: ['Mundschutz', 'Face mask', 'Mund-Nasen-Schutz', 'Surgical mask'],
    category: 'MED',
    subCategory: '医疗/防护',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['口罩', '面罩'],
    riskDescription: '医用口罩(Type I/II/IIR)需MDR合规。FFP2/FFP3需PPE认证。民用/时尚口罩需明确标注非医用。混淆类别导致严重后果。',
    legalBasis: 'MDR / PPE Regulation (EU) 2016/425 / EN 14683 / EN 149',
    alternatives: ['Community mask', 'Fashion face cover', 'Non-medical face covering'],
    tips: '严禁暗示医用防护等级。标题需注明：Community Mask / Non-medical'
  },
  {
    id: 'MED-006',
    keyword: 'Medical Device',
    localizedKeywords: { DE: 'Medizinprodukt', FR: 'Dispositif médical' },
    variants: ['Medizinprodukt', 'Medical grade', 'Clinical grade', 'Hospital grade'],
    category: 'MED',
    subCategory: '医疗器械',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'IT', 'ES'],
    commonProducts: ['血压计', '体温计', '助听器', '矫形器'],
    riskDescription: '标注"Medical Device"的产品必须有MDR分类、CE标志(由公告机构Notified Body审核)、UDI编码、欧盟授权代表等。',
    legalBasis: 'MDR (EU) 2017/745',
    alternatives: ['Health monitoring device (如非医疗)', 'Wellness device'],
    tips: 'MDR合规成本极高(几万到几十万欧元)，慎入此赛道'
  },
  {
    id: 'MED-007',
    keyword: 'Anti-Aging',
    localizedKeywords: { DE: 'Anti-Aging', FR: 'Anti-âge' },
    variants: ['Anti-wrinkle', 'Anti-Falten', 'Rejuvenating', 'Verjüngend'],
    category: 'MED',
    subCategory: '化妆品功效',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['面霜', '精华', '眼霜'],
    riskDescription: '化妆品功效声明必须有科学证据支持(如仪器测试、消费者测试)。"Removes wrinkles"暗示结构性改变，可能越线到医疗。',
    legalBasis: 'Cosmetic Regulation (EC) 1223/2009, Common Criteria for Claims',
    alternatives: ['Reduces the appearance of fine lines', 'Helps skin look younger'],
    tips: '措辞关键："reduces appearance of"而非"removes/eliminates"'
  },
  {
    id: 'MED-008',
    keyword: 'Supplement',
    localizedKeywords: { DE: 'Nahrungsergänzungsmittel', FR: 'Complément alimentaire' },
    variants: ['Dietary supplement', 'Food supplement', 'Vitamine'],
    category: 'MED',
    subCategory: '食品/健康',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'GB'],
    commonProducts: ['维生素', '蛋白粉', '鱼油', '益生菌'],
    riskDescription: '食品补充剂在每个EU成员国的通报/注册要求不同(DE: BVL, FR: DGCCRF, IT: Ministry of Health)。健康声明需在EFSA批准的清单中。',
    legalBasis: 'Food Supplement Directive 2002/46/EC, Health Claims Regulation (EC) 1924/2006',
    alternatives: ['如实标注，确保健康声明在EFSA approved list中'],
    tips: '德国需向BVL通报，意大利需向卫生部注册。各国允许的成分清单不同'
  },
  {
    id: 'MED-009',
    keyword: 'Boosts Immunity',
    localizedKeywords: { DE: 'Stärkt das Immunsystem', FR: 'Renforce l\'immunité' },
    variants: ['Immune booster', 'Strengthens immune system', 'Immunstärkend'],
    category: 'MED',
    subCategory: '健康声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['保健品', '蜂蜜', '茶', '精油'],
    riskDescription: '只有EFSA批准的特定维生素/矿物质可以声称"contributes to the normal function of the immune system"，且措辞必须完全一致。',
    legalBasis: 'Health Claims Regulation (EC) 1924/2006',
    alternatives: ['Vitamin C contributes to the normal function of the immune system (EFSA approved)'],
    tips: '使用EFSA EU Register of Health Claims中的精确措辞'
  },
  {
    id: 'MED-010',
    keyword: 'CBD',
    localizedKeywords: { DE: 'CBD', FR: 'CBD' },
    variants: ['Cannabidiol', 'Hemp oil', 'Cannabis oil', 'Hanföl'],
    category: 'MED',
    subCategory: '管控物质',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'GB'],
    commonProducts: ['CBD油', '面霜', '软糖'],
    riskDescription: '各国法律差异巨大。化妆品中CBD可能合法，但口服CBD产品在多数EU国家属于Novel Food需要授权。亚马逊政策也在变化中。',
    legalBasis: 'Novel Food Regulation (EU) 2015/2283, National drug laws',
    alternatives: ['Hemp seed oil (不含CBD)', 'Hanfsamenöl'],
    tips: '亚马逊欧洲站政策多变，建议回避整个品类'
  },
  {
    id: 'MED-011',
    keyword: 'Detox',
    localizedKeywords: { DE: 'Entgiftung', FR: 'Détox' },
    variants: ['Detoxify', 'Cleanse', 'Entgiften', 'Body cleanse'],
    category: 'MED',
    subCategory: '健康声明',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['茶', '果汁', '补充剂', '足贴'],
    riskDescription: '"Detox"暗示排除体内毒素，是未经EFSA批准的健康声明。德国消费者保护组织经常对此类声明发起警告(Abmahnung)。',
    legalBasis: 'Health Claims Regulation (EC) 1924/2006',
    alternatives: ['Refreshing', 'Revitalizing', 'Purifying (限化妆品)'],
    tips: '没有EFSA批准的"detox"声明。此词在食品/补充剂中是禁区'
  },
  {
    id: 'MED-012',
    keyword: 'Collagen',
    localizedKeywords: { DE: 'Kollagen', FR: 'Collagène' },
    variants: ['Kollagen', 'Collagène', 'Collagen peptides'],
    category: 'MED',
    subCategory: '健康声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['补充剂', '面霜', '饮品'],
    riskDescription: '口服胶原蛋白的健康声明(如"改善皮肤弹性")未获EFSA批准。化妆品中胶原蛋白的功效声明需科学证据支持。',
    legalBasis: 'Health Claims Regulation / Cosmetic Regulation',
    alternatives: ['Contains collagen (不做功效声明)', 'With hydrolyzed collagen peptides'],
    tips: '可以说含有胶原蛋白，但不能声称功效'
  },
  {
    id: 'MED-013',
    keyword: 'EMS',
    localizedKeywords: { DE: 'EMS-Gerät' },
    variants: ['Electrical muscle stimulation', 'Muscle stimulator'],
    category: 'MED',
    subCategory: '医疗器械边界',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['EMS腹肌贴', 'EMS健身仪'],
    riskDescription: '如声称治疗功效(如肌肉康复)则归类为医疗器械。仅用于健身/塑形可能不归MDR，但需要CE(LVD+EMC)认证。',
    legalBasis: 'MDR (if medical claims), LVD 2014/35/EU',
    alternatives: ['Muscle trainer', 'Fitness device'],
    tips: '严格区分健身用途和医疗用途的文案'
  },
  {
    id: 'MED-014',
    keyword: 'UV Sterilizer',
    localizedKeywords: { DE: 'UV-Sterilisator', FR: 'Stérilisateur UV' },
    variants: ['UV disinfection', 'UV sanitizer', 'Germicidal UV'],
    category: 'MED',
    subCategory: '生物杀灭',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'NL'],
    commonProducts: ['UV消毒灯', '牙刷消毒器', '手机消毒器'],
    riskDescription: 'UV消毒设备如果声称杀菌功效，归BPR管辖。此外UV-C辐射对人体有害，需符合光生物安全标准(IEC 62471)。',
    legalBasis: 'BPR (EU) 528/2012, IEC 62471',
    alternatives: ['UV cleaning light (避免使用sterilizer/disinfection)'],
    tips: 'UV-C产品是RAPEX(欧盟危险产品预警)高频产品'
  },
  {
    id: 'MED-015',
    keyword: 'Melatonin',
    localizedKeywords: { DE: 'Melatonin', FR: 'Mélatonine' },
    variants: [],
    category: 'MED',
    subCategory: '管控物质',
    riskLevel: 5,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['助眠补充剂', '软糖'],
    riskDescription: '德国将Melatonin >1mg/dose归类为药品(需处方)。食品补充剂中允许的剂量因国家而异，英国相对宽松。',
    legalBasis: 'German Medicinal Products Act (AMG), Food Supplement Directive',
    alternatives: ['Sleep support supplement (不含褪黑素或低剂量)'],
    tips: '在DE站销售含褪黑素的产品风险极高'
  },

  // ============================================================
  // === TOY 玩具安全 (Toys & Baby Products) ===
  // ============================================================
  {
    id: 'TOY-001',
    keyword: 'Puzzles',
    localizedKeywords: { DE: 'Puzzle', FR: 'Puzzle' },
    variants: ['Jigsaw puzzle', 'Jigsaw'],
    category: 'TOY',
    subCategory: '拼图',
    riskLevel: 2,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['拼图'],
    riskDescription: '需确认是否包含小部件(Small parts)。含小部件的产品不适合3岁以下儿童，需标注年龄警告。',
    legalBasis: 'EN71-1 Mechanical and physical properties',
    alternatives: ['Jigsaw'],
    tips: '必须标注推荐年龄和小部件警告'
  },
  {
    id: 'TOY-002',
    keyword: 'Teether',
    localizedKeywords: { DE: 'Beißring', FR: 'Anneau de dentition', IT: 'Massaggiagengive' },
    variants: ['Teething ring', 'Teething toy', 'Beißspielzeug'],
    category: 'TOY',
    subCategory: '婴儿用品',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'NL'],
    commonProducts: ['牙胶', '磨牙玩具'],
    riskDescription: '归类为0-3岁玩具，需最严格的化学+物理测试。EN71-1/2/3必须全部通过。特别关注BPA(已禁)、Phthalates(六种禁用)、Nitrosamines(EN71-12)。',
    legalBasis: 'EN71-1, 2, 3, 9, 12; REACH Annex XVII Entry 51/52',
    alternatives: ['Sensory toy (但实际仍需完整测试)'],
    tips: '高危中的高危。没有全套EN71+REACH测试报告绝对不要做'
  },
  {
    id: 'TOY-003',
    keyword: 'Magnetic',
    localizedKeywords: { DE: 'Magnetisch', FR: 'Magnétique' },
    variants: ['Magnets', 'Magnetic tiles', 'Magnetic balls', 'Magnetkugeln'],
    category: 'TOY',
    subCategory: '磁铁玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'NL', 'SE'],
    commonProducts: ['磁力片', '磁力球', '磁力积木'],
    riskDescription: '高通量磁铁(>50kG²mm²)如被吞食是致命的(肠穿孔)。RAPEX每年召回数十款磁铁玩具。部分国家已禁止小型强力磁铁作为玩具销售。',
    legalBasis: 'EN71-1 §8.24, Toy Safety Directive',
    alternatives: ['Magnetic tiles (需确保磁铁不可脱落)'],
    tips: '必须有"Warning: Contains magnets"。磁力球(Buckyballs类)在多个国家已被禁止作为玩具'
  },
  {
    id: 'TOY-004',
    keyword: 'Balloon',
    localizedKeywords: { DE: 'Luftballon', FR: 'Ballon', IT: 'Palloncino', ES: 'Globo' },
    variants: ['Balloons', 'Latex balloon', 'Foil balloon'],
    category: 'TOY',
    subCategory: '气球',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['乳胶气球', '铝膜气球', '气球套装'],
    riskDescription: '乳胶气球需特殊警告语(未充气/破裂气球有窒息风险)。8岁以下儿童需成人监督。警告语必须印在包装上。',
    legalBasis: 'Toy Safety Directive 2009/48/EC, EN71-1',
    alternatives: ['Party decoration (非玩具定位)'],
    tips: '警告语(DE)："Kinder unter 8 Jahren können an nicht aufgeblasenen oder geplatzten Ballons ersticken."'
  },
  {
    id: 'TOY-005',
    keyword: 'Slime',
    localizedKeywords: { DE: 'Schleim', FR: 'Slime', IT: 'Slime' },
    variants: ['Putty', 'Glibber', 'Fluffy slime', 'Cloud slime'],
    category: 'TOY',
    subCategory: '化学玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'ES', 'GB', 'NL'],
    commonProducts: ['史莱姆', '彩泥', '水晶泥'],
    riskDescription: '硼(Boron)含量是检测重点。EN71-3迁移限值极低(300mg/kg slime material)。RAPEX大量召回案例。实际上大多数市售Slime都超标。',
    legalBasis: 'EN71-3 Migration of elements, REACH',
    alternatives: ['Play dough (需确认合规)'],
    tips: '硼迁移限值300mg/kg极难达标。此品类建议回避'
  },
  {
    id: 'TOY-006',
    keyword: 'Finger Paint',
    localizedKeywords: { DE: 'Fingerfarbe', FR: 'Peinture au doigt' },
    variants: ['Fingerfarben', 'Finger paints'],
    category: 'TOY',
    subCategory: '化学玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['手指画颜料'],
    riskDescription: '需符合EN71-7(手指画颜料专门标准)。要求含苦味剂(Denatonium Benzoate)防止儿童吞食。防腐剂种类和含量有严格限制。',
    legalBasis: 'EN71-7 Finger paints',
    alternatives: ['Washable paint (需标注Not for finger painting if not compliant)'],
    tips: '必须含苦味剂防止吞食。成分表必须完整标注'
  },
  {
    id: 'TOY-007',
    keyword: 'Trampoline',
    localizedKeywords: { DE: 'Trampolin', FR: 'Trampoline', IT: 'Trampolino' },
    variants: ['Mini trampoline', 'Kindertrampolin'],
    category: 'TOY',
    subCategory: '运动玩具',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['蹦床', '家用蹦床'],
    riskDescription: '玩具蹦床需符合EN71-14(蹦床玩具)。承重、稳定性、防护网测试标准不同于成人蹦床(EN 13219)。',
    legalBasis: 'EN71-14 Trampolines for domestic use',
    alternatives: ['Jump pad', 'Bouncing mat'],
    tips: '需围网安全测试。年龄限制和最大体重需明确标注'
  },
  {
    id: 'TOY-008',
    keyword: 'Costume',
    localizedKeywords: { DE: 'Kostüm', FR: 'Déguisement', IT: 'Costume' },
    variants: ['Dressing up', 'Fancy dress', 'Verkleidung', 'Halloween costume'],
    category: 'TOY',
    subCategory: '角色扮演',
    riskLevel: 5,
    affectedSites: ['GB', 'DE', 'FR'],
    commonProducts: ['儿童服装', '万圣节服装', '角色扮演服'],
    riskDescription: '儿童化装服在EU被视为玩具，必须通过EN71-2燃烧性能测试(火焰传播速度限制)。同时需满足纺织品法规(成分标签)。',
    legalBasis: 'EN71-2 Flammability, Textile Regulation',
    alternatives: ['Outfit', 'Dress-up set'],
    tips: '万圣节服装是EN71-2燃烧测试重灾区。披风、裙子尤其危险'
  },
  {
    id: 'TOY-009',
    keyword: 'Walkie Talkie',
    localizedKeywords: { DE: 'Funkgerät', FR: 'Talkie-walkie' },
    variants: ['Two-way radio', 'Funkgerät für Kinder'],
    category: 'TOY',
    subCategory: '电子玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['儿童对讲机'],
    riskDescription: '虽是玩具，但因使用无线频率需要RED(Radio Equipment Directive)认证。频率必须使用PMR446(免许可)。同时需EN71玩具认证。',
    legalBasis: 'RED Directive 2014/53/EU, ETSI EN 300 296, Toy Safety Directive',
    alternatives: ['Toy radio'],
    tips: 'RED + EN71 双重认证要求。频率/功率不合规可被没收'
  },
  {
    id: 'TOY-010',
    keyword: 'Squishy',
    localizedKeywords: { DE: 'Squishy' },
    variants: ['Slow rising', 'Slow rising squishy', 'Squeeze toy'],
    category: 'TOY',
    subCategory: '解压玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'DK', 'SE', 'NL'],
    commonProducts: ['解压玩具', '慢回弹玩具'],
    riskDescription: '极易释放有害溶剂(甲苯、二甲苯等)。丹麦曾全面下架并禁止销售。造型模仿食物的额外风险(误食)。',
    legalBasis: 'REACH / Toy Safety Directive / National bans',
    alternatives: ['Stress ball (非PU foam材质)'],
    tips: '因为像食物(汉堡、甜甜圈造型)，小部件和误食风险叠加。建议远离此品类'
  },
  {
    id: 'TOY-011',
    keyword: 'Laser',
    localizedKeywords: { DE: 'Laser', FR: 'Laser' },
    variants: ['Laser pointer', 'Laser pen', 'Laserpointer'],
    category: 'TOY',
    subCategory: '光学玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'GB', 'FR', 'IT'],
    commonProducts: ['激光笔', '激光玩具', '激光陀螺'],
    riskDescription: '玩具中仅允许Class 1激光(<0.39mW)。Class 2及以上激光严禁用于玩具。高功率激光笔在部分国家被禁止或限制销售。',
    legalBasis: 'EN 60825-1, Toy Safety Directive, EN71-1',
    alternatives: ['LED light toy'],
    tips: '绝不要卖带>Class 1激光的玩具。多个卖家因此被刑事追诉'
  },
  {
    id: 'TOY-012',
    keyword: 'Ride-on',
    localizedKeywords: { DE: 'Rutscherfahrzeug', FR: 'Porteur' },
    variants: ['Balance bike', 'Ride-on toy', 'Bobby car', 'Laufrad'],
    category: 'TOY',
    subCategory: '骑乘玩具',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['滑行车', '平衡车', '扭扭车'],
    riskDescription: '承重测试、稳定性测试、刹车(如有)测试按EN71-1。电动骑乘玩具额外需要电气安全(EN62115)。',
    legalBasis: 'EN71-1, EN62115 (if electric)',
    alternatives: ['Baby walker'],
    tips: '注意区分电动和非电动的测试标准差异。Bobby Car是德国商标'
  },
  {
    id: 'TOY-013',
    keyword: 'Drone',
    localizedKeywords: { DE: 'Drohne', FR: 'Drone' },
    variants: ['Quadcopter', 'Mini drone', 'Spielzeugdrohne'],
    category: 'TOY',
    subCategory: '飞行玩具',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['玩具无人机', '迷你无人机'],
    riskDescription: '玩具无人机需同时符合玩具安全指令和航空法规(EASA)。<250g可免注册但仍有飞行限制。带摄像头的需考虑隐私(GDPR)。',
    legalBasis: 'EASA Regulations, Toy Safety Directive, GDPR',
    alternatives: ['Flying toy (clarify weight/capabilities)'],
    tips: '<250g且无摄像头的限制最少。在说明书中需包含当地飞行规则'
  },
  {
    id: 'TOY-014',
    keyword: 'Bath Book',
    localizedKeywords: { DE: 'Badebuch', FR: 'Livre de bain' },
    variants: ['Bath toy book', 'Waterproof book'],
    category: 'TOY',
    subCategory: '婴儿用品',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'NL'],
    commonProducts: ['洗澡书', '防水绘本'],
    riskDescription: '软塑(PVC/EVA)材料是Phthalates(邻苯二甲酸酯)重灾区。REACH Annex XVII Entry 51/52限制六种邻苯在儿童用品中的使用(<0.1%)。',
    legalBasis: 'REACH Annex XVII Entry 51/52, EN71-3',
    alternatives: ['Waterproof book (non-PVC material)'],
    tips: '必须过邻苯测试。建议使用EVA/TPU替代PVC(但EVA也需测试)'
  },
  {
    id: 'TOY-015',
    keyword: 'Wooden Toy',
    localizedKeywords: { DE: 'Holzspielzeug', FR: 'Jouet en bois' },
    variants: ['Wood toy', 'Holzspielzeug', 'Natural wood toy'],
    category: 'TOY',
    subCategory: '木制玩具',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['积木', '拼图', '木制火车'],
    riskDescription: '木材需甲醛(Formaldehyde)测试。油漆/涂层需重金属迁移测试(EN71-3)。胶水需检测。天然木材也可能含砷等元素。',
    legalBasis: 'EN71-3, EN71-9, Formaldehyde Regulation',
    alternatives: ['Wood block set'],
    tips: '实木产品注意甲醛。复合板(MDF/HDF)更需关注'
  },
  {
    id: 'TOY-016',
    keyword: 'Plush',
    localizedKeywords: { DE: 'Plüschtier', FR: 'Peluche', IT: 'Peluche' },
    variants: ['Stuffed animal', 'Teddy', 'Kuscheltier', 'Soft toy'],
    category: 'TOY',
    subCategory: '毛绒玩具',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['毛绒玩具', '公仔', '安抚玩偶'],
    riskDescription: '接缝强度(Seam strength)、小部件(眼睛/鼻子)拉力测试、填充物安全性是挂号主因。0-3岁用途需通过更严格的测试模板(Template A)。',
    legalBasis: 'EN71-1 Small parts, EN71-2 Flammability',
    alternatives: ['Soft toy'],
    tips: '塑料眼睛必须承受90N拉力不脱落。建议使用刺绣眼睛替代'
  },
  {
    id: 'TOY-017',
    keyword: 'Activity Mat',
    localizedKeywords: { DE: 'Spielmatte', FR: 'Tapis d\'éveil' },
    variants: ['Play mat', 'Gym mat', 'Foam puzzle mat', 'Krabbelmatte'],
    category: 'TOY',
    subCategory: '游戏垫',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'BE', 'NL'],
    commonProducts: ['泡沫拼图垫', '爬行垫', '游戏垫'],
    riskDescription: 'EVA泡沫拼图垫常含Formamide(甲酰胺)。法国(2014)和比利时有甲酰胺限量法规(<200ppm)。此外拼接部分可能脱落成小部件。',
    legalBasis: 'French Decree on Formamide (Dec 2014), EN71-1',
    alternatives: ['One-piece floor mat (non-foam)', 'PU play mat'],
    tips: 'EVA拼图垫需测甲酰胺。法国限值<200ppm，比利时<200ppm'
  },
  {
    id: 'TOY-018',
    keyword: 'Projectile',
    localizedKeywords: { DE: 'Projektil', FR: 'Projectile' },
    variants: ['Gun', 'Shooter', 'Dart gun', 'Pistole', 'Blaster'],
    category: 'TOY',
    subCategory: '发射玩具',
    riskLevel: 5,
    affectedSites: ['GB', 'DE', 'FR'],
    commonProducts: ['软弹枪', '水枪', '弓箭玩具'],
    riskDescription: '动能限值(EN71-1 §4.17)。吸盘弹射物需通过吸附力测试防止窒息。仿真枪外观有额外限制(不能模仿真枪)。',
    legalBasis: 'EN71-1 §4.17 Projectiles, Firearms legislation',
    alternatives: ['Dart blaster', 'Foam shooter'],
    tips: '不要做仿真枪外观。英国对仿真枪法律极为严格(VCRA 2006)'
  },
  {
    id: 'TOY-019',
    keyword: 'Chemistry Set',
    localizedKeywords: { DE: 'Chemiebaukasten', FR: 'Coffret de chimie' },
    variants: ['Science kit', 'Experiment set', 'Experimentierkasten'],
    category: 'TOY',
    subCategory: '实验玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['实验套装', '科学套装', '水晶种植套装'],
    riskDescription: '属于EN71-4(实验玩具)范畴。化学品清单、用量、警告语要求极严。需附带安全数据表(SDS)。',
    legalBasis: 'EN71-4 Experimental sets for chemistry',
    alternatives: ['STEM learning kit (避开化学品)'],
    tips: '涉及化学品的玩具套装合规成本极高'
  },
  {
    id: 'TOY-020',
    keyword: 'Rattle',
    localizedKeywords: { DE: 'Rassel', FR: 'Hochet', IT: 'Sonaglio' },
    variants: ['Baby rattle', 'Babyrassel'],
    category: 'TOY',
    subCategory: '婴儿用品',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['摇铃', '手摇铃'],
    riskDescription: '手柄形状需通过喉部测试模板(Template A/B)，防止噎死。重量不能过重。填充物不能散落。声压级不能过高(≤80dB)。',
    legalBasis: 'EN71-1 §5.2 Rattles, §4.6 Small parts',
    alternatives: ['Baby shaker'],
    tips: '形状设计必须防吞咽。这是0岁+玩具中最高危的品类之一'
  },
  {
    id: 'TOY-021',
    keyword: 'Water Beads',
    localizedKeywords: { DE: 'Wasserperlen', FR: 'Perles d\'eau' },
    variants: ['Orbeez', 'Gel beads', 'Hydrogel beads', 'Gelperlen'],
    category: 'TOY',
    subCategory: '危险玩具',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'NL', 'SE'],
    commonProducts: ['水宝宝', '水弹枪弹药'],
    riskDescription: '吞食后在体内膨胀可致命(肠梗阻)。多国已禁止作为玩具销售。EU正推进全面禁令。"Orbeez"是商标。',
    legalBasis: 'Toy Safety Directive, RAPEX notifications, Proposed EU ban',
    alternatives: ['避免此品类'],
    tips: 'CPSC(美国)和EU都在推进禁令。已有多起儿童死亡案例'
  },
  {
    id: 'TOY-022',
    keyword: 'Fidget Spinner',
    localizedKeywords: { DE: 'Fidget Spinner' },
    variants: ['Hand spinner', 'Finger spinner'],
    category: 'TOY',
    subCategory: '解压玩具',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['指尖陀螺'],
    riskDescription: '如含有纽扣电池(LED款)需符合电池安全要求。小部件(轴承)脱落风险。含铅轴承案例导致大规模召回。',
    legalBasis: 'EN71-1, Battery Directive',
    alternatives: ['Stress toy'],
    tips: '金属轴承需测试重金属含量'
  },
  {
    id: 'TOY-023',
    keyword: 'Baby Monitor',
    localizedKeywords: { DE: 'Babyphone', FR: 'Babyphone' },
    variants: ['Babyphone', 'Baby camera'],
    category: 'TOY',
    subCategory: '婴儿设备',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['婴儿监视器'],
    riskDescription: '非玩具但婴儿相关。需RED(无线)认证。WiFi款涉及GDPR(数据传输安全)。线缆需防勒颈(≥1m距离婴儿床)。',
    legalBasis: 'RED Directive, LVD, GDPR',
    alternatives: ['Child monitoring camera'],
    tips: '说明书需注明线缆放置距离要求'
  },
  {
    id: 'TOY-024',
    keyword: 'Crib Mobile',
    localizedKeywords: { DE: 'Mobile', FR: 'Mobile musical' },
    variants: ['Baby mobile', 'Musical mobile'],
    category: 'TOY',
    subCategory: '婴儿用品',
    riskLevel: 4,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['床铃', '婴儿床挂件'],
    riskDescription: '线绳/绳索长度限制(防勒颈)。固定夹承重测试。小部件测试。音乐盒音量限制。',
    legalBasis: 'EN71-1, EN71-2',
    alternatives: ['Hanging decoration (非玩具定位，但如面向婴儿仍适用)'],
    tips: '所有可能接触婴儿的产品默认按0-3岁玩具标准'
  },
  {
    id: 'TOY-025',
    keyword: 'Cot Bumper',
    localizedKeywords: { DE: 'Nestchen', FR: 'Tour de lit' },
    variants: ['Crib bumper', 'Bed bumper', 'Bettumrandung'],
    category: 'TOY',
    subCategory: '婴儿安全',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['婴儿床围'],
    riskDescription: '多国已禁止或限制销售(窒息风险)。法国2024年起可能全面禁止。亚马逊部分站点已限制上架。',
    legalBasis: 'National bans, Consumer safety recommendations',
    alternatives: ['Breathable mesh liner', 'Sleep sack'],
    tips: '极高风险品类，多国在禁止中。建议不做'
  },
  {
    id: 'TOY-026',
    keyword: 'Night Light',
    localizedKeywords: { DE: 'Nachtlicht', FR: 'Veilleuse' },
    variants: ['Kids night light', 'Kindernachtlicht', 'Projector light'],
    category: 'TOY',
    subCategory: '儿童照明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['儿童小夜灯', '投影灯'],
    riskDescription: '如果设计面向儿童(动物造型等)，可能被归类为玩具(需EN71)。电气安全(LVD/EN60598)。USB充电款需注意电池安全。',
    legalBasis: 'EN71 (if toy), EN60598 (lighting), LVD',
    alternatives: ['Decorative lamp'],
    tips: '明确定位：是灯具(EN60598)还是玩具(EN71)?不同标准不同'
  },

  // ============================================================
  // === ELE 电子与信号 (Electronics) ===
  // ============================================================
  {
    id: 'ELE-001',
    keyword: 'Bluetooth',
    localizedKeywords: {},
    variants: ['BT', 'BLE', 'Bluetooth 5.0'],
    category: 'ELE',
    subCategory: '无线通信',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR', 'IT', 'ES'],
    commonProducts: ['耳机', '音箱', '手表', '追踪器'],
    riskDescription: 'Bluetooth SIG拥有商标权和认证体系(BQB)。未通过BQB认证的产品不得使用Bluetooth名称/Logo。仅说"Compatible"也有灰色地带。',
    legalBasis: 'Bluetooth SIG Trademark Policy, RED Directive',
    alternatives: ['Wireless', 'BT compatible (谨慎使用)'],
    tips: 'BQB认证费用较高且会随机构与服务商报价变化。无证时标题和图片都不要出现Bluetooth字样和Logo'
  },
  {
    id: 'ELE-002',
    keyword: 'WiFi 6E',
    localizedKeywords: {},
    variants: ['Wi-Fi 6E', 'WiFi 6 GHz'],
    category: 'ELE',
    subCategory: '无线通信',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['路由器', '网卡', '智能家居'],
    riskDescription: '6GHz频段在EU的开放程度不同于美国(EU仅开放lower 6GHz: 5945-6425MHz)。需RED认证更新。功率限制也不同。',
    legalBasis: 'RED Directive 2014/53/EU, ECC Decision (20)01',
    alternatives: ['WiFi 6', 'Check frequency compatibility'],
    tips: '确认目标国6GHz频段开放情况和功率限制'
  },
  {
    id: 'ELE-003',
    keyword: 'Laser Hair Removal',
    localizedKeywords: { DE: 'Laser Haarentfernung', FR: 'Épilation laser' },
    variants: ['IPL', 'Intense Pulsed Light', 'IPL device'],
    category: 'ELE',
    subCategory: '美容设备',
    riskLevel: 5,
    affectedSites: ['DE', 'NL', 'FR'],
    commonProducts: ['脱毛仪', 'IPL美容仪'],
    riskDescription: 'IPL≠Laser，技术原理不同。标"Laser"可能将产品错误分类为更高风险设备。部分国家将IPL家用设备归类为Class I医疗器械(如intended for medical purpose)。',
    legalBasis: 'MDR (if medical claims), LVD, IEC 60335-2-113',
    alternatives: ['IPL hair removal device', 'Light-based hair removal'],
    tips: 'IPL不是Laser，标题中严禁使用"Laser"。文案中避免医疗功效声明'
  },
  {
    id: 'ELE-004',
    keyword: 'Jammer',
    localizedKeywords: { DE: 'Störsender', FR: 'Brouilleur' },
    variants: ['Signal jammer', 'GPS jammer', 'WiFi jammer', 'Frequenzstörer'],
    category: 'ELE',
    subCategory: '违禁设备',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'IT', 'ES', 'NL', 'SE', 'PL', 'BE'],
    commonProducts: ['信号干扰器'],
    riskDescription: '信号干扰设备在全EU完全违法。销售、持有和使用均构成刑事犯罪。罚款可达数百万欧元。',
    legalBasis: 'Radio Equipment Directive, National telecommunications laws',
    alternatives: ['无合法替代品'],
    tips: '绝对禁区。亚马逊也严禁上架'
  },
  {
    id: 'ELE-005',
    keyword: 'USB-C',
    localizedKeywords: {},
    variants: ['Type-C', 'USB Type C'],
    category: 'ELE',
    subCategory: '充电接口',
    riskLevel: 2,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['手机', '平板', '耳机', '充电器'],
    riskDescription: 'EU通用充电器法规(Common Charger Directive)要求从2024年12月28日起，特定电子设备必须使用USB-C充电。标注需准确反映充电协议(PD等)。',
    legalBasis: 'Directive (EU) 2022/2380 Common Charger',
    alternatives: ['确保产品符合通用充电器指令'],
    tips: '2024年12月28日起生效。笔记本电脑延至2026年4月'
  },
  {
    id: 'ELE-006',
    keyword: 'Power Bank',
    localizedKeywords: { DE: 'Powerbank', FR: 'Batterie externe' },
    variants: ['Portable charger', 'External battery', 'Externe Batterie'],
    category: 'ELE',
    subCategory: '电池产品',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['充电宝', '移动电源'],
    riskDescription: '锂电池运输受限(UN38.3测试报告)。容量标注需准确(额定容量vs电芯容量)。新EU电池法规(2023)要求EPR注册、碳足迹声明等。',
    legalBasis: 'EU Battery Regulation 2023/1542, UN38.3, LVD',
    alternatives: ['Portable charging device'],
    tips: '德国eBattery注册。容量需标注额定(Rated)容量而非电芯容量'
  },
  {
    id: 'ELE-007',
    keyword: 'FM Transmitter',
    localizedKeywords: { DE: 'FM Transmitter', FR: 'Émetteur FM' },
    variants: ['FM sender', 'Radio transmitter'],
    category: 'ELE',
    subCategory: '无线设备',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['车载FM发射器'],
    riskDescription: '发射功率和频率范围需符合当地无线电管理规定。RED认证必须。不同国家允许的FM频率范围可能不同。',
    legalBasis: 'RED Directive, ETSI EN 301 357',
    alternatives: ['Bluetooth car adapter (如有BQB认证)'],
    tips: '确认发射功率符合各国限制'
  },
  {
    id: 'ELE-008',
    keyword: 'Spy Camera',
    localizedKeywords: { DE: 'Spionagekamera', FR: 'Caméra espion' },
    variants: ['Hidden camera', 'Mini camera', 'Versteckte Kamera', 'Nanny cam'],
    category: 'ELE',
    subCategory: '隐私设备',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'NL'],
    commonProducts: ['微型摄像头', '伪装摄像头'],
    riskDescription: '在德国，秘密录音/录像设备是违法的(StGB §201)。标题含"Spy/Hidden"的摄像头可能导致下架甚至刑事调查。GDPR也有严格规定。',
    legalBasis: 'German StGB §201/201a, GDPR, French Penal Code',
    alternatives: ['Security camera', 'Mini camera (不要用spy/hidden)'],
    tips: '德国法律禁止销售专为秘密监控设计的设备。"Nanny Cam"也有法律风险'
  },
  {
    id: 'ELE-009',
    keyword: 'E-Cigarette',
    localizedKeywords: { DE: 'E-Zigarette', FR: 'Cigarette électronique' },
    variants: ['Vape', 'Vaporizer', 'E-Shisha', 'Dampfer'],
    category: 'ELE',
    subCategory: '管控产品',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'IT', 'ES'],
    commonProducts: ['电子烟', '烟弹'],
    riskDescription: 'TPD(烟草制品指令)严格管控。液体体积≤2ml(烟弹)、≤10ml(补充装)。尼古丁浓度≤20mg/ml。需健康警告。各国额外限制不同。',
    legalBasis: 'TPD Directive 2014/40/EU, National implementation laws',
    alternatives: ['无法规避，需完全合规'],
    tips: '亚马逊大部分站点禁止销售电子烟产品'
  },
  {
    id: 'ELE-010',
    keyword: 'Smart Watch',
    localizedKeywords: { DE: 'Smartwatch', FR: 'Montre connectée' },
    variants: ['Fitness tracker', 'Wearable'],
    category: 'ELE',
    subCategory: '可穿戴设备',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['智能手表', '健身手环'],
    riskDescription: '如有健康监测功能(血压、心率、血氧)，功效声明需谨慎。不能声称"医疗级准确度"。儿童智能手表在德国因隐私问题被禁(可被用于监听)。',
    legalBasis: 'RED, GDPR, German Telecommunications Act (TKG)',
    alternatives: ['Activity tracker', 'Fitness band'],
    tips: '德国2017年禁止可被用于秘密监听的儿童手表。Bundesnetzagentur执法'
  },
  {
    id: 'ELE-011',
    keyword: 'Plug Adapter',
    localizedKeywords: { DE: 'Reiseadapter', FR: 'Adaptateur de voyage' },
    variants: ['Travel adapter', 'Steckdosenadapter', 'Socket converter'],
    category: 'ELE',
    subCategory: '电气安全',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['转换插头', '旅行适配器'],
    riskDescription: '欧洲各国插座标准不同(Schuko/Type F, French/Type E, UK/Type G)。需符合相应安全标准。不能同时暴露不同国家的插脚(防触电)。',
    legalBasis: 'LVD 2014/35/EU, National wiring regulations',
    alternatives: ['Universal travel adapter (需逐国认证)'],
    tips: 'RAPEX经常召回不安全的旅行适配器'
  },
  {
    id: 'ELE-012',
    keyword: 'Voltage Converter',
    localizedKeywords: { DE: 'Spannungswandler' },
    variants: ['Step down transformer', 'Power converter'],
    category: 'ELE',
    subCategory: '电气安全',
    riskLevel: 3,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['变压器', '电压转换器'],
    riskDescription: '需符合LVD安全标准。功率标注需准确。CE标志(DoC)必须。过载/短路保护必须有。',
    legalBasis: 'LVD 2014/35/EU',
    alternatives: [],
    tips: '确保功率标注为实际持续功率而非峰值功率'
  },
  {
    id: 'ELE-013',
    keyword: 'MFi',
    localizedKeywords: {},
    variants: ['Made for iPhone', 'Made for iPad', 'Lightning cable'],
    category: 'ELE',
    subCategory: '品牌授权',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'GB', 'IT', 'ES'],
    commonProducts: ['数据线', '充电器', '配件'],
    riskDescription: 'MFi(Made for iPhone/iPad/iPod)是Apple授权程序。未经授权使用MFi标志或声称MFi认证即构成商标侵权。Apple维权极为积极。',
    legalBasis: 'Apple MFi Program, Trademark Law',
    alternatives: ['Compatible with iPhone (需注意措辞)', 'Charging cable for Phone'],
    tips: '标题中不要出现Apple, iPhone, iPad等商标(除非用"compatible with"格式)'
  },
  {
    id: 'ELE-014',
    keyword: 'Qi Certified',
    localizedKeywords: {},
    variants: ['Qi wireless charging', 'Qi-certified'],
    category: 'ELE',
    subCategory: '认证声明',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['无线充电器', '无线充电宝'],
    riskDescription: 'Qi是WPC(Wireless Power Consortium)的注册商标和认证程序。未通过WPC认证不得使用Qi Logo或声称"Qi Certified"。',
    legalBasis: 'WPC Trademark Policy',
    alternatives: ['Wireless charger', 'Wireless charging compatible'],
    tips: '无WPC认证时不要使用Qi标志'
  },
  {
    id: 'ELE-015',
    keyword: 'Alexa Compatible',
    localizedKeywords: {},
    variants: ['Works with Alexa', 'Alexa-enabled', 'Google Home compatible'],
    category: 'ELE',
    subCategory: '品牌声明',
    riskLevel: 3,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['智能家居', '智能插座', '灯泡'],
    riskDescription: '"Works with Alexa"需通过Amazon认证程序。"Works with Google Home"需通过Google认证。未经认证声称兼容可能导致listing被下架。',
    legalBasis: 'Amazon/Google certification programs',
    alternatives: ['Voice control compatible', 'Smart home device'],
    tips: '如确实通过认证，可以使用官方badge'
  },

  // ============================================================
  // === FOD 食品接触 (Food Contact Materials) ===
  // ============================================================
  {
    id: 'FOD-001',
    keyword: 'Food Grade',
    localizedKeywords: { DE: 'Lebensmittelecht', FR: 'Alimentaire', IT: 'Per alimenti' },
    variants: ['Lebensmittelecht', 'Food safe', 'Lebensmittelsicher'],
    category: 'FOD',
    subCategory: '食品接触',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['餐盒', '水瓶', '硅胶模具', '保鲜膜'],
    riskDescription: '德国需LFGB认证(杯叉标志♺🍴)。法国需DGCCRF测试。所有食品接触材料需符合EU 1935/2004框架法规和具体材料的执行法规(如塑料: EU 10/2011)。',
    legalBasis: 'EU 1935/2004, LFGB (Germany), EU 10/2011 (Plastics)',
    alternatives: ['Safe for food contact (需有测试报告)'],
    tips: '杯叉标志必须印在产品上。需提供Migration test(迁移测试)报告'
  },
  {
    id: 'FOD-002',
    keyword: 'Cutting Board',
    localizedKeywords: { DE: 'Schneidebrett', FR: 'Planche à découper' },
    variants: ['Chopping board', 'Schneidbrett'],
    category: 'FOD',
    subCategory: '厨房用品',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['竹制砧板', '木质砧板', '塑料砧板'],
    riskDescription: '竹/木拼接胶水甲醛迁移是主要风险。竹制品需关注矿物油(MOSH/MOAH)迁移。塑料砧板需符合EU 10/2011。',
    legalBasis: 'LFGB, EU 1935/2004, BfR Recommendations',
    alternatives: [],
    tips: '整竹/整木比拼接板安全。胶水选择至关重要'
  },
  {
    id: 'FOD-003',
    keyword: 'Silicone Mold',
    localizedKeywords: { DE: 'Silikonform', FR: 'Moule en silicone' },
    variants: ['Baking mold', 'Cake mold', 'Backform'],
    category: 'FOD',
    subCategory: '烘焙用品',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['硅胶模具', '蛋糕模具', '冰格'],
    riskDescription: '硅胶需测试挥发性有机物(VOC)和总迁移量。德国BfR对硅胶食品接触制品有特殊建议(first use需高温空烤4小时)。',
    legalBasis: 'EU 1935/2004, BfR Recommendation XV (Silicones)',
    alternatives: ['Food-safe silicone baking mold'],
    tips: '产品说明需包含首次使用前的清洗/烘烤指导'
  },
  {
    id: 'FOD-004',
    keyword: 'Bamboo Cup',
    localizedKeywords: { DE: 'Bambusbecher', FR: 'Gobelet en bambou' },
    variants: ['Bamboo fiber cup', 'Bamboo coffee cup', 'Bambusbecher'],
    category: 'FOD',
    subCategory: '食品接触',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'NL', 'BE', 'GB'],
    commonProducts: ['竹纤维杯', '竹纤维餐具'],
    riskDescription: '竹粉/竹纤维+三聚氰胺树脂制品在EU已被禁止！因为竹粉不在EU批准的塑料添加剂清单中，且高温下释放甲醛和三聚氰胺超标。',
    legalBasis: 'EU 10/2011 (bamboo not authorized), RASFF notifications',
    alternatives: ['Pure bamboo (natural, not fiber composite)', 'Stainless steel', 'Glass'],
    tips: '这是近年最大的食品接触材料合规事件之一。竹纤维+树脂杯子已被全面禁止'
  },
  {
    id: 'FOD-005',
    keyword: 'Cast Iron Pan',
    localizedKeywords: { DE: 'Gusseisenpfanne', FR: 'Poêle en fonte' },
    variants: ['Cast iron skillet', 'Gusseisenpfanne', 'Iron pan'],
    category: 'FOD',
    subCategory: '厨房用品',
    riskLevel: 2,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['铸铁锅', '铸铁煎锅'],
    riskDescription: '需符合EU 1935/2004。铁和锰的迁移量需在安全限值内。搪瓷涂层需测试重金属(铅、镉)迁移。',
    legalBasis: 'EU 1935/2004, Council of Europe Resolution on Metals',
    alternatives: [],
    tips: '搪瓷涂层的铅镉测试很重要'
  },
  {
    id: 'FOD-006',
    keyword: 'Lunch Box',
    localizedKeywords: { DE: 'Brotdose', FR: 'Boîte à lunch', IT: 'Portapranzo' },
    variants: ['Bento box', 'Brotdose', 'Food container'],
    category: 'FOD',
    subCategory: '食品容器',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['饭盒', '便当盒'],
    riskDescription: '塑料类需EU 10/2011全面迁移测试。儿童用途的需按EN71+食品接触双重标准。密封圈材料也需测试。',
    legalBasis: 'EU 10/2011, EU 1935/2004',
    alternatives: [],
    tips: '如标注"Microwave safe"需有相应测试(高温迁移)'
  },
  {
    id: 'FOD-007',
    keyword: 'Drinking Straw',
    localizedKeywords: { DE: 'Trinkhalm', FR: 'Paille' },
    variants: ['Reusable straw', 'Metal straw', 'Strohhalm'],
    category: 'FOD',
    subCategory: '食品接触',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['不锈钢吸管', '硅胶吸管', '竹吸管'],
    riskDescription: '单次使用塑料吸管在EU已被禁止(SUP Directive)。替代材料(不锈钢/硅胶/竹)需食品接触合规测试。',
    legalBasis: 'SUP Directive 2019/904, EU 1935/2004',
    alternatives: ['Reusable drinking straw (确保材质合规)'],
    tips: '不锈钢吸管需注意镍释放。竹吸管需防霉处理测试'
  },
  {
    id: 'FOD-008',
    keyword: 'Non-Stick',
    localizedKeywords: { DE: 'Antihaft', FR: 'Antiadhésif' },
    variants: ['Antihaftbeschichtung', 'Non-stick coating'],
    category: 'FOD',
    subCategory: '涂层',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['煎锅', '烤盘', '电饭煲内胆'],
    riskDescription: 'PFAS限制提案可能影响所有含PTFE涂层的厨具。标注"PFOA-free"是合规底线(PFOA已被禁)。需关注PFAS全面限制的立法进展。',
    legalBasis: 'REACH (PFOA restriction), PFAS restriction proposal',
    alternatives: ['Ceramic coating', 'PFAS-free non-stick'],
    tips: '关注EU PFAS全面限制提案的立法进展(预计2025-2027)'
  },

  // ============================================================
  // === MKT 营销话术 (Marketing Claims) ===
  // ============================================================
  {
    id: 'MKT-001',
    keyword: 'Best',
    localizedKeywords: { DE: 'Beste', FR: 'Meilleur', IT: 'Migliore', ES: 'Mejor' },
    variants: ['Best quality', 'Best selling', 'Bestseller', 'Top quality', 'Premium quality'],
    category: 'MKT',
    subCategory: '夸大宣传',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'GB'],
    commonProducts: ['所有产品'],
    riskDescription: '"Best"是绝对性声明(Superlative)，在德国广告法中需有可验证的证据支持。竞争对手可据此发起Abmahnung(警告信)。',
    legalBasis: 'German UWG §5, UCPD 2005/29/EC',
    alternatives: ['High quality', 'Premium', 'Excellent (less risky but still broad)'],
    tips: '德国Abmahnung律师专门搜索这类绝对化词汇。成本：每次约€1,000-3,000'
  },
  {
    id: 'MKT-002',
    keyword: 'Unique',
    localizedKeywords: { DE: 'Einzigartig', FR: 'Unique' },
    variants: ['One of a kind', 'Only', 'Exclusive'],
    category: 'MKT',
    subCategory: '夸大宣传',
    riskLevel: 2,
    affectedSites: ['DE'],
    commonProducts: ['所有产品'],
    riskDescription: '"Einzigartig"(Unique)如果市场上存在相似产品则构成虚假广告。',
    legalBasis: 'UWG §5',
    alternatives: ['Distinctive', 'Special design'],
    tips: '除非真的全球唯一，否则不要用'
  },
  {
    id: 'MKT-003',
    keyword: 'Forever',
    localizedKeywords: { DE: 'Für immer', FR: 'Pour toujours' },
    variants: ['Lifetime', 'Eternal', 'Indestructible', 'Unbreakable', 'Unzerstörbar'],
    category: 'MKT',
    subCategory: '夸大宣传',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['工具', '行李箱', '手机壳'],
    riskDescription: '"Unbreakable/Indestructible"是可以被测试验证的声明。如果产品在正常使用中损坏，消费者可以此为依据要求赔偿。',
    legalBasis: 'UCPD, German BGB (Product liability)',
    alternatives: ['Durable', 'Long-lasting', 'Heavy-duty', 'Robust'],
    tips: '避免绝对化的耐久性声明'
  },
  {
    id: 'MKT-004',
    keyword: 'Military Grade',
    localizedKeywords: { DE: 'Militärqualität' },
    variants: ['MIL-STD', 'MIL-SPEC', 'Military standard', 'Tactical'],
    category: 'MKT',
    subCategory: '夸大宣传',
    riskLevel: 3,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['手机壳', '手电筒', '手表', '背包'],
    riskDescription: '声称符合MIL-STD-810G等军标需有实际测试报告。空泛使用"Military grade"没有法律意义。部分国家对军事相关营销有限制。',
    legalBasis: 'UCPD, Misleading advertising provisions',
    alternatives: ['Drop-tested', 'Shock-resistant', 'Impact-protected'],
    tips: '如有MIL-STD测试报告可以标注具体标准号'
  },
  {
    id: 'MKT-005',
    keyword: 'Waterproof',
    localizedKeywords: { DE: 'Wasserdicht', FR: 'Étanche', IT: 'Impermeabile' },
    variants: ['Wasserdicht', 'Water resistant', 'Splash proof', 'IPX7', 'IP68'],
    category: 'MKT',
    subCategory: '性能声明',
    riskLevel: 3,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['手表', '手机壳', '音箱', '背包', '夹克'],
    riskDescription: '"Waterproof"和"Water resistant"含义不同。电子产品应标注IP等级(如IPX7)。纺织品应标注水柱压力(如5000mm)。模糊使用可导致高退货率和投诉。',
    legalBasis: 'UCPD, IEC 60529 (IP ratings)',
    alternatives: ['Water-resistant (IP rating)', 'Splash-proof (IPX4)', 'Rain-resistant'],
    tips: '标注具体IP等级比笼统的"Waterproof"安全得多'
  },
  {
    id: 'MKT-006',
    keyword: 'Hospital Grade',
    localizedKeywords: { DE: 'Krankenhausqualität' },
    variants: ['Medical grade', 'Clinical grade', 'Pharmaceutical grade'],
    category: 'MKT',
    subCategory: '夸大宣传',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['清洁用品', '床品', '手套'],
    riskDescription: '"Hospital/Medical grade"暗示产品适用于医疗环境，可能将产品归类为医疗器械(MDR)。非医疗产品使用此词汇构成误导。',
    legalBasis: 'MDR, UCPD',
    alternatives: ['Professional grade', 'High-standard quality'],
    tips: '避免任何医疗相关的等级声明'
  },
  {
    id: 'MKT-007',
    keyword: 'Original',
    localizedKeywords: { DE: 'Original', FR: 'Original' },
    variants: ['Authentic', 'Genuine', 'OEM'],
    category: 'MKT',
    subCategory: '真伪声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['配件', '替换件', '墨盒'],
    riskDescription: '"Original"在配件市场中暗示来自原始品牌制造商(OEM)。第三方兼容产品标"Original"是商标侵权和欺诈。',
    legalBasis: 'Trademark Law, UCPD',
    alternatives: ['Compatible replacement for...', 'Alternative for...'],
    tips: '第三方产品严禁使用"Original"。正确写法："Compatible replacement for [Brand]"'
  },
  {
    id: 'MKT-008',
    keyword: 'Luxury',
    localizedKeywords: { DE: 'Luxus', FR: 'Luxe', IT: 'Lusso' },
    variants: ['Luxus', 'Designer', 'High-end', 'Luxuriös'],
    category: 'MKT',
    subCategory: '夸大宣传',
    riskLevel: 2,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['首饰', '手表', '皮具', '家居用品'],
    riskDescription: '在低价产品上使用"Luxury/Designer"可能构成误导。法国对"Luxury goods"概念有特殊的法律和文化敏感性。',
    legalBasis: 'UCPD',
    alternatives: ['Elegant', 'Premium', 'Sophisticated'],
    tips: '€20的产品标"Luxury"会导致消费者预期落差和差评'
  },
  {
    id: 'MKT-009',
    keyword: 'Free',
    localizedKeywords: { DE: 'Kostenlos', FR: 'Gratuit', IT: 'Gratis' },
    variants: ['Gratis', 'Kostenlos', 'Free gift', 'Geschenk'],
    category: 'MKT',
    subCategory: '促销话术',
    riskLevel: 3,
    affectedSites: ['DE', 'GB'],
    commonProducts: ['赠品', '套装'],
    riskDescription: '标注"Free gift"如果赠品成本已包含在售价中则构成误导。"Buy one get one free"需符合促销法规。',
    legalBasis: 'UCPD, Price Indication Directive',
    alternatives: ['Includes additional...', 'Bonus item included'],
    tips: '赠品需明确标注，不能用赠品来提高定价'
  },
  {
    id: 'MKT-010',
    keyword: 'Handmade',
    localizedKeywords: { DE: 'Handgemacht', FR: 'Fait main', IT: 'Fatto a mano' },
    variants: ['Handcrafted', 'Hand-sewn', 'Handarbeit', 'Artisanal'],
    category: 'MKT',
    subCategory: '工艺声明',
    riskLevel: 3,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['首饰', '皮具', '陶瓷', '蜡烛'],
    riskDescription: '机器生产的产品标"Handmade"构成欺诈。亚马逊有专门的Handmade品类和审核程序。非Handmade品类中使用此词也有风险。',
    legalBasis: 'UCPD, Amazon Handmade Policy',
    alternatives: ['Carefully crafted', 'Artisan-inspired'],
    tips: '如真正手工制作，可以加入Amazon Handmade项目'
  },

  // ============================================================
  // === GEO 地理标识 (Geographical Indications) ===
  // ============================================================
  {
    id: 'GEO-001',
    keyword: 'Swiss Made',
    localizedKeywords: { DE: 'Schweizer Qualität', FR: 'Fabriqué en Suisse' },
    variants: ['Swiss quality', 'Swiss engineered', 'Swiss design'],
    category: 'GEO',
    subCategory: '原产地',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'GB'],
    commonProducts: ['手表', '刀具', '巧克力', '奶酪'],
    riskDescription: '受Swissness legislation严格保护。手表："Swiss Made"要求60%以上成本在瑞士产生，机芯瑞士制造且装壳在瑞士。其他产品：80%制造成本在瑞士。',
    legalBasis: 'Swissness Act (Markenschutzgesetz), Bilateral agreements with EU',
    alternatives: ['Swiss design (如设计确实在瑞士)', 'Inspired by Swiss precision'],
    tips: '非瑞士产品禁用十字标志和"Swiss"声明。瑞士联邦知识产权局积极执法'
  },
  {
    id: 'GEO-002',
    keyword: 'Champagne',
    localizedKeywords: { DE: 'Champagner', FR: 'Champagne' },
    variants: ['Champagner', 'Champaign'],
    category: 'GEO',
    subCategory: 'PDO保护',
    riskLevel: 5,
    affectedSites: ['FR', 'DE', 'IT', 'ES', 'GB'],
    commonProducts: ['起泡酒', '酒杯', '派对用品'],
    riskDescription: 'Champagne是受PDO(Protected Designation of Origin)保护的地理标识。只有法国香槟地区生产的起泡酒才能称为Champagne。连"Champagne-style"也被禁止。',
    legalBasis: 'EU PDO Regulation 1151/2012, Madrid Agreement',
    alternatives: ['Sparkling wine', 'Prosecco (仅限意大利产)', 'Cava (仅限西班牙产)'],
    tips: '即使是"Champagne glass"(香槟杯)也有被CIVC投诉的案例。建议用"Sparkling wine glass"'
  },
  {
    id: 'GEO-003',
    keyword: 'Parmesan',
    localizedKeywords: { DE: 'Parmesan', FR: 'Parmesan', IT: 'Parmigiano' },
    variants: ['Parmigiano', 'Parmigiano-Reggiano'],
    category: 'GEO',
    subCategory: 'PDO保护',
    riskLevel: 5,
    affectedSites: ['IT', 'DE', 'FR'],
    commonProducts: ['奶酪', '奶酪刨', '调味料'],
    riskDescription: 'Parmigiano-Reggiano是PDO保护产品。"Parmesan"在EU法院判例中也被认定为受保护名称(不能用于非产区奶酪)。',
    legalBasis: 'EU PDO Regulation 1151/2012, ECJ Case C-132/05',
    alternatives: ['Italian-style hard cheese', 'Grana-type cheese'],
    tips: '奶酪刨等工具标题中也不要写"Parmesan grater"，用"Hard cheese grater"'
  },
  {
    id: 'GEO-004',
    keyword: 'Scotch',
    localizedKeywords: {},
    variants: ['Scotch Whisky', 'Scottish'],
    category: 'GEO',
    subCategory: 'GI保护',
    riskLevel: 5,
    affectedSites: ['GB', 'DE', 'FR'],
    commonProducts: ['威士忌', '酒杯', '酒具'],
    riskDescription: '"Scotch Whisky"受法律严格保护。只有在苏格兰按特定规则生产的威士忌才能使用。相关酒具也需注意。',
    legalBasis: 'Scotch Whisky Regulations 2009, EU GI protection',
    alternatives: ['Whisky glass (不标产区)'],
    tips: 'Scotch Whisky Association积极维权'
  },
  {
    id: 'GEO-005',
    keyword: 'Meissen',
    localizedKeywords: { DE: 'Meißen' },
    variants: ['Meißen', 'Meissener Porzellan'],
    category: 'GEO',
    subCategory: '品牌/产地',
    riskLevel: 5,
    affectedSites: ['DE'],
    commonProducts: ['瓷器', '餐具'],
    riskDescription: 'Meissen是德国著名瓷器品牌(Staatliche Porzellan-Manufaktur Meissen GmbH)的商标。非授权产品禁用。',
    legalBasis: 'German Trademark Law',
    alternatives: ['Fine porcelain', 'European-style porcelain'],
    tips: '勿将产地和品牌混淆'
  },
  {
    id: 'GEO-006',
    keyword: 'Solingen',
    localizedKeywords: {},
    variants: ['Solinger Qualität', 'Solingen steel'],
    category: 'GEO',
    subCategory: '产地标识',
    riskLevel: 5,
    affectedSites: ['DE'],
    commonProducts: ['刀具', '剪刀', '指甲刀'],
    riskDescription: '"Solingen"刀具产地标识受德国法律严格保护(Solingenverordnung)。产品主要加工步骤(锻造、磨削、打磨等)必须在Solingen完成。',
    legalBasis: 'Solingenverordnung (German Solingen Decree)',
    alternatives: ['German-style knife', 'Stainless steel knife'],
    tips: '中国制造的刀具标"Solingen"将面临刑事起诉'
  },
  {
    id: 'GEO-007',
    keyword: 'Murano',
    localizedKeywords: {},
    variants: ['Murano glass', 'Murano-style'],
    category: 'GEO',
    subCategory: '产地标识',
    riskLevel: 4,
    affectedSites: ['IT', 'DE', 'FR'],
    commonProducts: ['玻璃制品', '首饰', '装饰品'],
    riskDescription: 'Murano玻璃受意大利法律保护。"Murano-style"在意大利站也可能被投诉。意大利当局积极打击假冒Murano产品。',
    legalBasis: 'Italian trademark/geographic indication protection',
    alternatives: ['Blown glass', 'Art glass', 'Venetian-inspired glass'],
    tips: '意大利对Murano产地标识保护极为重视'
  },
  {
    id: 'GEO-008',
    keyword: 'Prosecco',
    localizedKeywords: {},
    variants: [],
    category: 'GEO',
    subCategory: 'PDO保护',
    riskLevel: 5,
    affectedSites: ['IT', 'DE', 'FR', 'GB'],
    commonProducts: ['起泡酒', '酒杯', '礼品套装'],
    riskDescription: 'Prosecco是受PDO/DOC保护的意大利起泡酒地理标识。只有威内托和弗留利-威尼斯朱利亚产区的产品才能使用。',
    legalBasis: 'EU PDO Regulation 1151/2012',
    alternatives: ['Sparkling wine', 'Italian sparkling wine'],
    tips: '连"Prosecco glass"也需谨慎'
  },
  {
    id: 'GEO-009',
    keyword: 'Darjeeling',
    localizedKeywords: {},
    variants: ['Darjeeling tea'],
    category: 'GEO',
    subCategory: 'GI保护',
    riskLevel: 4,
    affectedSites: ['DE', 'GB', 'FR'],
    commonProducts: ['茶叶', '茶具'],
    riskDescription: 'Darjeeling茶受GI保护。只有来自印度大吉岭地区的茶叶才能使用此名称。Tea Board of India积极维权。',
    legalBasis: 'EU GI protection, Bilateral agreements',
    alternatives: ['Indian highland tea', 'Mountain tea'],
    tips: '非产区茶叶标"Darjeeling flavor"也有风险'
  },
  {
    id: 'GEO-010',
    keyword: 'Bavarian',
    localizedKeywords: { DE: 'Bayerisch', FR: 'Bavarois' },
    variants: ['Bayrisch', 'Bavaria', 'Bayern'],
    category: 'GEO',
    subCategory: '产地声明',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['啤酒', '香肠', '啤酒杯', '传统服饰'],
    riskDescription: '"Bavarian"在德国常指巴伐利亚州。但并非所有 Bavarian-style 产品都产自该地。可能误导消费者。',
    legalBasis: 'German Trademark Law',
    alternatives: ['Traditional style', 'Regional recipe'],
    tips: '建议明确标注具体产地或原料来源'
  }
];

// 辅助函数：按分类获取词条
export function getWordsByCategory(categoryCode: string) {
  return RESTRICTED_WORDS_DATABASE.filter(w => w.category === categoryCode);
}

// 辅助函数：按风险等级获取词条
export function getWordsByRiskLevel(level: number) {
  return RESTRICTED_WORDS_DATABASE.filter(w => w.riskLevel === level);
}

// 辅助函数：按站点获取词条
export function getWordsBySite(siteCode: string) {
  return RESTRICTED_WORDS_DATABASE.filter(w => w.affectedSites.includes(siteCode));
}
