// 欧洲本土化高危词库常量
// 基于亚马逊欧洲站多年运营经验整理

// 风险等级定义
export const RISK_LEVELS = {
  1: { label: '提示/Info', icon: 'ℹ️', color: 'blue' },
  2: { label: '注意/Caution', icon: '⚠️', color: 'yellow' },
  3: { label: '警告/Warning', icon: '⚡', color: 'orange' },
  4: { label: '严重/Severe', icon: '🚫', color: 'red' },
  5: { label: '致命/Fatal', icon: '☠️', color: 'red' }
};

// 词库分类
export const WORD_CATEGORIES = {
  MAT: { label: '材质成分', icon: 'fa-shirt', color: 'purple' },
  CMP: { label: '合规声明', icon: 'fa-certificate', color: 'amber' },
  ENV: { label: '环保声明', icon: 'fa-leaf', color: 'green' },
  MED: { label: '医疗健康', icon: 'fa-heart-pulse', color: 'red' },
  ELE: { label: '电子产品', icon: 'fa-bolt', color: 'blue' },
  TOY: { label: '母婴玩具', icon: 'fa-baby', color: 'pink' },
  FOD: { label: '食品接触', icon: 'fa-utensils', color: 'orange' },
  MKT: { label: '营销话术', icon: 'fa-bullhorn', color: 'indigo' },
  GEO: { label: '地理标识', icon: 'fa-map-marker', color: 'teal' },
  IPR: { label: '知识产权', icon: 'fa-copyright', color: 'slate' }
};

// 欧洲站点
export const EU_SITES = ['DE', 'FR', 'IT', 'ES', 'NL', 'SE', 'PL', 'BE', 'UK'];

// 高危词库数据库
export const RESTRICTED_WORDS_DATABASE = [
  // === MAT 材质成分 (Textiles & Materials) ===
  {
    id: 'MAT-001',
    keyword: 'Bamboo',
    localizedKeywords: { DE: 'Bambus', FR: 'Bambou', IT: 'Bambù', ES: 'Bambú' },
    variants: ['Bambus', 'Bambou', 'Bambù', 'Bambú'],
    category: 'MAT',
    subCategory: '纺织标签',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'UK'],
    commonProducts: ['内裤', '袜子', '床品'],
    riskDescription: '德国严查！竹纤维本质是粘胶，标"Bamboo"属欺诈。',
    legalBasis: 'Textile Regulation (EU) 1007/2011',
    alternatives: ['Viscose (from Bamboo)', 'Rayon from Bamboo'],
    tips: 'DE站必须写 "Viskose aus Bambuszellstoff"'
  },
  {
    id: 'MAT-002',
    keyword: 'Lycra',
    localizedKeywords: { DE: 'Elastan', FR: 'Élasthanne', IT: 'Elastan', ES: 'Elastano' },
    variants: ['Elastan', 'Élasthanne', 'Elastam', 'Elastano', 'Spandex'],
    category: 'MAT',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['瑜伽裤', '泳衣'],
    riskDescription: 'Lycra是商标，Spandex是美式写法，欧洲需用Elastane。',
    legalBasis: 'EU 1007/2011',
    alternatives: ['Elastane', 'Elasthan (DE)', 'Élasthanne (FR)'],
    tips: '欧洲站慎用Spandex，首选Elastane'
  },
  {
    id: 'MAT-003',
    keyword: 'PU Leather',
    localizedKeywords: { DE: 'Kunstleder', FR: 'Similicuir', IT: 'Ecopelle', ES: 'Cuero sintético' },
    variants: ['Kunstleder', 'Cuir synthétique', 'Faux leather', 'Ecopelle'],
    category: 'MAT',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['皮包', '沙发'],
    riskDescription: '易误导为真皮。DE站严禁将"Leder"与"PU/Echt"混淆。',
    legalBasis: 'UCPD 2005/29/EC',
    alternatives: ['Synthetic Leather', 'Faux Leather', 'Kunstleder (DE)'],
    tips: 'Listing中避免出现单独的"Leather"'
  },
  {
    id: 'MAT-004',
    keyword: 'Alcantara',
    localizedKeywords: {},
    variants: [],
    category: 'MAT',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT'],
    commonProducts: ['汽车内饰', '手机壳'],
    riskDescription: 'Alcantara是注册商标，非授权产品禁用。',
    legalBasis: 'Trademark Law',
    alternatives: ['Suede-like fabric', 'Microfiber'],
    tips: '极高危商标词'
  },
  {
    id: 'MAT-005',
    keyword: 'Pashmina',
    localizedKeywords: { DE: 'Kaschmir', FR: 'Cachemire' },
    variants: ['Cashmere', 'Kaschmir', 'Cachemire'],
    category: 'MAT',
    riskLevel: 4,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['围巾'],
    riskDescription: '必须是100%山羊绒才能叫Cashmere/Pashmina。',
    legalBasis: 'Textile Regulation',
    alternatives: ['Soft synthetic scarf', 'Cashmere-feel'],
    tips: '一旦检测不含羊绒，直接封号'
  },
  {
    id: 'MAT-006',
    keyword: 'Silk',
    localizedKeywords: { DE: 'Seide', FR: 'Soie', IT: 'Seta', ES: 'Seda' },
    variants: ['Seide', 'Soie', 'Seta', 'Seda'],
    category: 'MAT',
    riskLevel: 4,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['睡衣', '枕套'],
    riskDescription: '必须依规定标注Silk/Synthetic，不能模糊叫"Silky"。',
    legalBasis: 'Textile Regulation',
    alternatives: ['Satin (如是聚酯)', 'Silk-like'],
    tips: 'Silky satin 这种写法在德国有风险'
  },
  {
    id: 'MAT-007',
    keyword: 'Modal',
    localizedKeywords: {},
    variants: [],
    category: 'MAT',
    riskLevel: 2,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['内衣'],
    riskDescription: 'Modal是通用词，但需确认为Lenzing Modal还是普通。',
    legalBasis: 'Textile Regulation',
    alternatives: ['Modal fibers'],
    tips: '建议写明 95% Modal, 5% Elastane'
  },
  {
    id: 'MAT-008',
    keyword: 'Chiffon',
    localizedKeywords: {},
    variants: [],
    category: 'MAT',
    riskLevel: 2,
    affectedSites: ['UK', 'DE'],
    commonProducts: ['连衣裙'],
    riskDescription: 'Chiffon是织造工艺非成分，需标明Polyester Chiffon。',
    legalBasis: 'Textile Regulation',
    alternatives: ['100% Polyester (Chiffon weave)'],
    tips: '不能只写Chiffon作为材质'
  },
  {
    id: 'MAT-009',
    keyword: 'Velcro',
    localizedKeywords: { DE: 'Klettverschluss', FR: 'Velcro' },
    variants: ['Klettverschluss', 'Scratch'],
    category: 'MAT',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'UK'],
    commonProducts: ['鞋子', '收纳带'],
    riskDescription: 'Velcro是魔术贴的商标名，非授权禁用。',
    legalBasis: 'Trademark Law',
    alternatives: ['Hook and loop fastener', 'Magic tape', 'Klettverschluss (DE)'],
    tips: '极易侵权，务必用Hook and Loop'
  },
  {
    id: 'MAT-010',
    keyword: 'Gore-Tex',
    localizedKeywords: {},
    variants: [],
    category: 'MAT',
    riskLevel: 5,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['冲锋衣', '登山鞋'],
    riskDescription: '知名防水面料商标。',
    legalBasis: 'Trademark Law',
    alternatives: ['Waterproof breathable fabric'],
    tips: '禁用Gore-Tex'
  },

  // === CMP 合规声明 (Compliance) ===
  {
    id: 'CMP-001',
    keyword: 'CE Certified',
    localizedKeywords: { DE: 'CE-zertifiziert', FR: 'Certifié CE' },
    variants: ['CE Approved', 'CE geprüft'],
    category: 'CMP',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES', 'UK'],
    commonProducts: ['电子', '玩具'],
    riskDescription: 'CE是法律底线，宣传"CE认证"暗示其他产品不合规，属不正当竞争。',
    legalBasis: 'UCPD 2005/29/EC',
    alternatives: ['不宣传CE', 'CE mark visible on product'],
    tips: '图片中可展示CE标，但文案别写'
  },
  {
    id: 'CMP-002',
    keyword: 'FDA Approved',
    localizedKeywords: {},
    variants: ['FDA Certified'],
    category: 'CMP',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'UK'],
    commonProducts: ['厨具', '美容仪'],
    riskDescription: 'FDA是美国机构，在欧洲宣传无效且可能误导。',
    legalBasis: 'Misleading Advertising',
    alternatives: ['LFGB compliant (DE)', 'Food grade'],
    tips: '欧洲认LFGB, DGCCRF(FR)'
  },
  {
    id: 'CMP-003',
    keyword: 'RoHS Compliant',
    localizedKeywords: { DE: 'RoHS-konform' },
    variants: [],
    category: 'CMP',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['电子'],
    riskDescription: '法定义务，不能作为独特卖点宣传。',
    legalBasis: 'UCPD',
    alternatives: ['删除宣传此类法定义务的词'],
    tips: '默认合规即可'
  },
  {
    id: 'CMP-004',
    keyword: 'TÜV Certified',
    localizedKeywords: { DE: 'TÜV geprüft' },
    variants: ['TÜV SÜD', 'TÜV Rheinland'],
    category: 'CMP',
    riskLevel: 5,
    affectedSites: ['DE'],
    commonProducts: ['汽配', '电器'],
    riskDescription: '除非真有TÜV证书且要在Listing注明证书号，否则由于"含有"TÜV而被投诉侵权。',
    legalBasis: 'Trademark / Certification Marks',
    alternatives: ['Safety tested'],
    tips: '德国人极认TÜV，但也极爱投诉造假'
  },
  {
    id: 'CMP-005',
    keyword: 'GS Mark',
    localizedKeywords: { DE: 'GS-Zeichen' },
    variants: ['Geprüfte Sicherheit'],
    category: 'CMP',
    riskLevel: 4,
    affectedSites: ['DE'],
    commonProducts: ['工具', '家电'],
    riskDescription: 'GS是德国安全认证，乱标会被巨额罚款。',
    legalBasis: 'ProdSG (German Product Safety Act)',
    alternatives: ['删除GS相关描述'],
    tips: '无证严禁提GS'
  },
  {
    id: 'CMP-006',
    keyword: 'Warranty',
    localizedKeywords: { DE: 'Garantie', FR: 'Garantie' },
    variants: ['Guarantee'],
    category: 'CMP',
    subCategory: '售后条款',
    riskLevel: 4,
    affectedSites: ['DE'],
    commonProducts: ['所有'],
    riskDescription: '德国站提"Garantie"必须附带完整保修条款链接/文本，否则违法。',
    legalBasis: 'German Civil Code (BGB)',
    alternatives: ['24-month customer support', 'Quality promise'],
    tips: '用"Warranty"必须极度小心，建议用Support'
  },
  {
    id: 'CMP-007',
    keyword: 'Free Shipping',
    localizedKeywords: { DE: 'Versandkostenfrei' },
    variants: [],
    category: 'CMP',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['FBA产品'],
    riskDescription: '如果是Prime本身就包邮，强调"Free Shipping"可能构成广告误导 (Self-evident)。',
    legalBasis: 'UCPD',
    alternatives: ['Fast delivery'],
    tips: 'Prime商品别特意强调包邮'
  },

  // === ENV 环保 (Environmental) ===
  {
    id: 'ENV-001',
    keyword: 'Eco-Friendly',
    localizedKeywords: { DE: 'Umweltfreundlich', FR: 'Écologique' },
    variants: ['Green', 'Nature friendly'],
    category: 'ENV',
    riskLevel: 4,
    affectedSites: ['DE', 'FR', 'UK'],
    commonProducts: ['全品类'],
    riskDescription: '欧盟绿色声明指令（Green Claims Directive）严打模糊环保词。',
    legalBasis: 'Green Claims Directive',
    alternatives: ['Made of 100% recycled PET', 'Energy efficient class A'],
    tips: '必须具体：哪里环保？怎么环保？'
  },
  {
    id: 'ENV-002',
    keyword: 'Biodegradable',
    localizedKeywords: { DE: 'Biologisch abbaubar', FR: 'Biodégradable' },
    variants: ['Degradable'],
    category: 'ENV',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'IT', 'ES'],
    commonProducts: ['垃圾袋', '餐具'],
    riskDescription: '必须符合EN 13432标准并持有OK Compost证书，法国禁止 ऑक्सी-degradable (氧化降解) 塑料。',
    legalBasis: 'Single-Use Plastics Directive',
    alternatives: ['Compostable (EN 13432 certified)'],
    tips: 'Ox0-degradable在欧洲是彻底违禁品'
  },
  {
    id: 'ENV-003',
    keyword: 'Carbon Neutral',
    localizedKeywords: { DE: 'Klimaneutral' },
    variants: ['CO2 Neutral'],
    category: 'ENV',
    riskLevel: 4,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['所有'],
    riskDescription: '需提供权威的碳补偿证书和计算依据。',
    legalBasis: 'Consumer Protection Laws',
    alternatives: ['Low carbon footprint'],
    tips: '没有证书别碰碳中和'
  },
  {
    id: 'ENV-004',
    keyword: 'BPA Free',
    localizedKeywords: { DE: 'BPA-frei', FR: 'Sans BPA' },
    variants: ['Bisphenol A free'],
    category: 'ENV',
    riskLevel: 3,
    affectedSites: ['FR'],
    commonProducts: ['奶瓶', '食品容器'],
    riskDescription: '法国法律禁止在食品接触包装上标注"Sans BPA"（因为法律已禁止BPA，标出反而是误导）。',
    legalBasis: 'Loi n° 2010-729 (France)',
    alternatives: ['Food grade material'],
    tips: '仅法国站：不要强调Sans BPA'
  },

  // === MED 医疗健康 (Medical) ===
  {
    id: 'MED-001',
    keyword: 'Cures',
    localizedKeywords: { DE: 'Heilt', FR: 'Guérit' },
    variants: ['Treats', 'Heals', 'Therapy'],
    category: 'MED',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'UK'],
    commonProducts: ['保健品', '按摩仪'],
    riskDescription: '暗示医疗功效，非药品/医疗器械禁用。',
    legalBasis: 'MDR / Medicinal Products Directive',
    alternatives: ['Supports', 'Helps maintain'],
    tips: '普通产品绝对不能写治愈'
  },
  {
    id: 'MED-002',
    keyword: 'Antibacterial',
    localizedKeywords: { DE: 'Antibakteriell', FR: 'Antibactérien' },
    variants: ['Antimicrobial', 'Antiviral'],
    category: 'MED',
    riskLevel: 5,
    affectedSites: ['DE', 'UK', 'SE'],
    commonProducts: ['袜子', '清洁用品'],
    riskDescription: '属生物杀灭剂 (Biocides)，需在欧盟ECHA注册并合规标注。',
    legalBasis: 'BPR (Biocidal Products Regulation)',
    alternatives: ['Hygienic', 'Easy to clean'],
    tips: '不仅仅是词，产品本身需合规'
  },
  {
    id: 'MED-003',
    keyword: 'Whitening',
    localizedKeywords: { DE: 'Aufhellung', FR: 'Blanchiment' },
    variants: ['Bleaching'],
    category: 'MED',
    riskLevel: 4,
    affectedSites: ['UK', 'DE'],
    commonProducts: ['牙贴', '护肤品'],
    riskDescription: '牙齿美白有过氧化氢浓度限制 (>0.1%受限)。',
    legalBasis: 'Cosmetic Regulation',
    alternatives: ['Brightening'],
    tips: '化妆品类目高危词'
  },
  {
    id: 'MED-004',
    keyword: 'Pain Relief',
    localizedKeywords: { DE: 'Schmerzlinderung' },
    variants: ['Anti-pain'],
    category: 'MED',
    riskLevel: 5,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['护具', '枕头'],
    riskDescription: '缓解疼痛是医疗功效，普通护具不能用。',
    legalBasis: 'MDR',
    alternatives: ['Comfortable support'],
    tips: '颈椎枕头最容易挂在这里'
  },
  {
    id: 'MED-005',
    keyword: 'Mask',
    localizedKeywords: { DE: 'Maske', FR: 'Masque' },
    variants: ['Mundschutz'],
    category: 'MED',
    riskLevel: 3,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['面罩'],
    riskDescription: '疫情后敏感词，分医用和民用，混淆会导致下架。',
    legalBasis: 'MDR / PPE Regulation',
    alternatives: ['Face cover', 'Community mask'],
    tips: '严禁暗示医用防护等级'
  },

  // === TOY 玩具安全 (Toys) - 扩充20+ ===
  {
    id: 'TOY-001',
    keyword: 'Puzzles',
    localizedKeywords: { DE: 'Puzzle' },
    variants: [],
    category: 'TOY',
    riskLevel: 2,
    affectedSites: ['DE'],
    commonProducts: ['拼图'],
    riskDescription: '需确认是否包含小部件，适用于3岁+。',
    legalBasis: 'EN71-1',
    alternatives: ['Jigsaw'],
    tips: '记得标年龄'
  },
  {
    id: 'TOY-002',
    keyword: 'Teether',
    localizedKeywords: { DE: 'Beißring', FR: 'Anneau de dentition' },
    variants: [],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'UK'],
    commonProducts: ['牙胶'],
    riskDescription: '归类为0-3岁玩具，需极严格化学+物理测试 (BPA, Phthalates, nitrosamines)。',
    legalBasis: 'EN71-1, 2, 3, 9, 12',
    alternatives: ['Sensory toy'],
    tips: '高危中的高危，没有全套报告别做'
  },
  {
    id: 'TOY-003',
    keyword: 'Magnetic',
    localizedKeywords: { DE: 'Magnetisch' },
    variants: ['Magnets'],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'UK'],
    commonProducts: ['磁力片'],
    riskDescription: '高通量磁铁如果被吞食是致命的。需符合磁通量限制。',
    legalBasis: 'EN71-1',
    alternatives: ['Magnetic tiles (需合规)'],
    tips: '一定要有"Warning: Contains magnets"'
  },
  {
    id: 'TOY-004',
    keyword: 'Balloon',
    localizedKeywords: { DE: 'Luftballon' },
    variants: [],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['气球'],
    riskDescription: '特殊的警告语要求（未充气/破裂气球窒息风险）。',
    legalBasis: 'Toy Safety Directive',
    alternatives: ['Party decoration'],
    tips: '警告语必须印在包装上'
  },
  {
    id: 'TOY-005',
    keyword: 'Slime',
    localizedKeywords: { DE: 'Schleim', FR: 'Slime' },
    variants: ['Putty', 'Glibber'],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'FR', 'ES'],
    commonProducts: ['史莱姆'],
    riskDescription: '硼(Boron)含量极易超标，各国抽查重点。',
    legalBasis: 'EN71-3 Migration of elements',
    alternatives: ['Play dough'],
    tips: '硼迁移限值极低(300mg/kg)，一般工厂做不到'
  },
  {
    id: 'TOY-006',
    keyword: 'Finger Paint',
    localizedKeywords: { DE: 'Fingerfarbe' },
    variants: [],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE'],
    commonProducts: ['颜料'],
    riskDescription: '需符合EN71-7防腐剂和苦味剂要求。',
    legalBasis: 'EN71-7',
    alternatives: ['Washable paint'],
    tips: '必须含苦味剂防止吞食'
  },
  {
    id: 'TOY-007',
    keyword: 'Trampoline',
    localizedKeywords: { DE: 'Trampolin' },
    variants: [],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE'],
    commonProducts: ['蹦床'],
    riskDescription: '需符合EN71-14家用蹦床标准。',
    legalBasis: 'EN71-14',
    alternatives: ['Jump pad'],
    tips: '需围网安全测试'
  },
  {
    id: 'TOY-008',
    keyword: 'Costume',
    localizedKeywords: { DE: 'Kostüm' },
    variants: ['Dressing up'],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['UK', 'DE'],
    commonProducts: ['儿童这类'],
    riskDescription: '视为玩具，需EN71-2燃烧性能测试。',
    legalBasis: 'EN71-2 Flammability',
    alternatives: ['Outfit'],
    tips: '万圣节服装是燃烧测试重灾区'
  },
  {
    id: 'TOY-009',
    keyword: 'Walkie Talkie',
    localizedKeywords: {},
    variants: [],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['儿童对讲机'],
    riskDescription: '虽是玩具，但需RED无线指令认证 (ETSI EN 300 296)。',
    legalBasis: 'RED Directive',
    alternatives: ['Toy radio'],
    tips: 'RED + EN71 双重认证'
  },
  {
    id: 'TOY-010',
    keyword: 'Squishy',
    localizedKeywords: {},
    variants: ['Slow rising'],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'DK'],
    commonProducts: ['解压玩具'],
    riskDescription: '极易释放有害溶剂，丹麦曾全面禁止。',
    legalBasis: 'REACH / Toy Safety',
    alternatives: ['Stress ball'],
    tips: '因为像食物，此时通过小部件测试更难'
  },
  {
    id: 'TOY-011',
    keyword: 'Laser',
    localizedKeywords: { DE: 'Laser' },
    variants: [],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['激光玩具'],
    riskDescription: '高等级激光严禁用于玩具（仅允许Class 1）。',
    legalBasis: 'EN 60825-1',
    alternatives: ['LED light'],
    tips: '绝不要卖带激光的玩具'
  },
  {
    id: 'TOY-012',
    keyword: 'Ride-on',
    localizedKeywords: { DE: 'Rutscherfahrzeug' },
    variants: ['Balance bike'],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE'],
    commonProducts: ['滑行车'],
    riskDescription: '承重和刹车测试标准不同。',
    legalBasis: 'EN71-1',
    alternatives: ['Baby walker'],
    tips: '分电动和非电动'
  },
  {
    id: 'TOY-013',
    keyword: 'Drone',
    localizedKeywords: { DE: 'Drohne' },
    variants: ['Quadcopte'],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['无人机'],
    riskDescription: '如果带摄像需标明隐私，且属于玩具指令还是航空法管辖需界定。',
    legalBasis: 'EASA Regulations',
    alternatives: ['Flying toy'],
    tips: '重量<250g限制少'
  },
  {
    id: 'TOY-014',
    keyword: 'Bath Book',
    localizedKeywords: { DE: 'Badebuch' },
    variants: [],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE'],
    commonProducts: ['洗澡书'],
    riskDescription: '软塑材料，Phthalates重灾区。',
    legalBasis: 'REACH Annex XVII',
    alternatives: ['Waterproof book'],
    tips: '必须过邻苯测试'
  },
  {
    id: 'TOY-015',
    keyword: 'Wooden Toy',
    localizedKeywords: { DE: 'Holzspielzeug' },
    variants: [],
    category: 'TOY',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['积木'],
    riskDescription: '木材需甲醛测试 (Formaldehyde)。油漆需重金属测试。',
    legalBasis: 'EN71-9',
    alternatives: ['Wood block'],
    tips: '实木产品注意甲醛'
  },
  {
    id: 'TOY-016',
    keyword: 'Plush',
    localizedKeywords: { DE: 'Plüschtier' },
    variants: ['Stuffed animal', 'Teddy'],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['毛绒玩具'],
    riskDescription: '拉力测试(Seam strength)和小部件(眼睛)脱落是挂号主因。',
    legalBasis: 'EN71-1',
    alternatives: ['Soft toy'],
    tips: '眼睛必须无法被拉下'
  },
  {
    id: 'TOY-017',
    keyword: 'Activity Mat',
    localizedKeywords: { DE: 'Spielmatte' },
    variants: ['Play mat', 'Gym'],
    category: 'TOY',
    riskLevel: 4,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['游戏垫'],
    riskDescription: '泡沫拼图垫(EVA)常含Formamide(甲酰胺)，法/比有限制。',
    legalBasis: 'French Decree on Formamide',
    alternatives: ['Floor mat'],
    tips: 'EVA材质需测甲酰胺'
  },
  {
    id: 'TOY-018',
    keyword: 'Projectile',
    localizedKeywords: {},
    variants: ['Gun', 'Shooter'],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['UK', 'DE'],
    commonProducts: ['发射玩具'],
    riskDescription: '动能限制，吸盘弹射物需测试吸附力防止窒息。',
    legalBasis: 'EN71-1',
    alternatives: ['Dart blaster'],
    tips: '不要做仿真枪'
  },
  {
    id: 'TOY-019',
    keyword: 'Chemistry Set',
    localizedKeywords: { DE: 'Chemiebaukasten' },
    variants: [],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE'],
    commonProducts: ['实验套装'],
    riskDescription: '属于EN71-4实验玩具，化学品清单极严。',
    legalBasis: 'EN71-4',
    alternatives: ['Science kit'],
    tips: ''
  },
  {
    id: 'TOY-020',
    keyword: 'Rattle',
    localizedKeywords: { DE: 'Rassel' },
    variants: [],
    category: 'TOY',
    riskLevel: 5,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['摇铃'],
    riskDescription: '手柄形状喉部测试 (Template A/B)，防噎死。',
    legalBasis: 'EN71-1',
    alternatives: ['Baby shaker'],
    tips: '形状设计必须防吞咽'
  },

  // === ELE 电子与信号 (Electronics) ===
  {
    id: 'ELE-001',
    keyword: 'Bluetooth',
    localizedKeywords: {},
    variants: [],
    category: 'ELE',
    riskLevel: 4,
    affectedSites: ['DE', 'UK', 'FR'],
    commonProducts: ['耳机', '音箱'],
    riskDescription: 'SIG拥有商标权。未BQB认证产品不能标Bluetooth，只能说Compatible。',
    legalBasis: 'Trademark / SIG Policy',
    alternatives: ['Wireless', 'BT compatible'],
    tips: 'BQB认证很贵，无证别标Logo'
  },
  {
    id: 'ELE-002',
    keyword: 'WiFi 6E',
    localizedKeywords: {},
    variants: [],
    category: 'ELE',
    riskLevel: 4,
    affectedSites: ['EU'],
    commonProducts: ['路由器'],
    riskDescription: '6GHz频段在部分非欧盟国家有不同限制，需RED更新标准。',
    legalBasis: 'RED Directive',
    alternatives: ['WiFi 6'],
    tips: '确认目标国频段开放'
  },
  {
    id: 'ELE-003',
    keyword: 'Laser Hair Removal',
    localizedKeywords: { DE: 'Laser Haarentfernung' },
    variants: ['IPL'],
    category: 'ELE',
    riskLevel: 5,
    affectedSites: ['DE', 'NL'],
    commonProducts: ['脱毛仪'],
    riskDescription: 'IPL和激光设备在医用/家用界限模糊，常需医械认证。',
    legalBasis: 'MDR',
    alternatives: ['IPL hair remover (慎用Laser)'],
    tips: 'IPL不是Laser，别乱写'
  },

  // === FOD 食品接触 (Food Contact) ===
  {
    id: 'FOD-001',
    keyword: 'Food Grade',
    localizedKeywords: { DE: 'Lebensmittelecht' },
    variants: [],
    category: 'FOD',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['餐盒'],
    riskDescription: '需LFGB标志（杯叉标）。',
    legalBasis: 'LFGB/EU 1935/2004',
    alternatives: ['Safe for food contact'],
    tips: '杯叉标志必须印在产品底'
  },
  {
    id: 'FOD-002',
    keyword: 'Cutting Board',
    localizedKeywords: { DE: 'Schneidebrett' },
    variants: [],
    category: 'FOD',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['竹板'],
    riskDescription: '竹木拼接胶水甲醛迁移。',
    legalBasis: 'LFGB',
    alternatives: [''],
    tips: '整竹比拼接安全'
  },

  // === IPR 知识产权 (IPR) ===
  {
    id: 'IPR-001',
    keyword: 'Compatible with',
    localizedKeywords: { DE: 'Kompatibel mit', FR: 'Compatible avec' },
    variants: ['For', 'Fits'],
    category: 'IPR',
    riskLevel: 3,
    affectedSites: ['DE'],
    commonProducts: ['配件'],
    riskDescription: '必须"Compatible"在前，品牌在后，不能写"iPhone Case"。',
    legalBasis: 'Trademark Law',
    alternatives: ['Case for iPhone'],
    tips: '写法：[Your Brand] Case compatible with iPhone 13'
  },
  {
    id: 'IPR-002',
    keyword: 'Swarovski',
    localizedKeywords: {},
    variants: ['Crystals from Swarovski'],
    category: 'IPR',
    riskLevel: 5,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['首饰'],
    riskDescription: '即使真用了施华洛世奇水晶，也严禁在标题用Swarovski品牌名（除非联名）。',
    legalBasis: 'Trademark Law',
    alternatives: ['Crystal necklace'],
    tips: '极高危，已停止向散户供货'
  },
  {
    id: 'IPR-003',
    keyword: 'Hula Hoop',
    localizedKeywords: { DE: 'Hula Hoop' },
    variants: [],
    category: 'IPR',
    riskLevel: 4,
    affectedSites: ['DE', 'UK'],
    commonProducts: ['健身圈'],
    riskDescription: 'Hula Hoop是Wham-O公司商标。',
    legalBasis: 'Trademark Law',
    alternatives: ['Fitness hoop', 'Exercise hoop', 'Gymnastikreifen (DE)'],
    tips: '用Fitness Hoop代替'
  },
  {
    id: 'IPR-004',
    keyword: 'Onesie',
    localizedKeywords: {},
    variants: [],
    category: 'IPR',
    riskLevel: 4,
    affectedSites: ['UK'],
    commonProducts: ['连体衣'],
    riskDescription: 'Gerber公司商标。',
    legalBasis: 'Trademark Law',
    alternatives: ['Bodysuit', 'Jumpsuit', 'Sleepsuit'],
    tips: '用Bodysuit'
  },
  {
    id: 'IPR-005',
    keyword: 'Frisbee',
    localizedKeywords: {},
    variants: [],
    category: 'IPR',
    riskLevel: 4,
    affectedSites: ['EU'],
    commonProducts: ['飞盘'],
    riskDescription: 'Wham-O商标。',
    legalBasis: 'Trademark Law',
    alternatives: ['Flying disc', 'Wurfscheibe (DE)'],
    tips: '用Flying disc'
  },

  // === GEO 地理标识 ===
  {
    id: 'GEO-001',
    keyword: 'Swiss Made',
    localizedKeywords: { DE: 'Schweizer Qualität' },
    variants: [],
    category: 'GEO',
    riskLevel: 5,
    affectedSites: ['DE', 'FR'],
    commonProducts: ['手表', '刀具'],
    riskDescription: '严格的瑞士法例保护(Swissness legislation)。',
    legalBasis: 'Swissness Act',
    alternatives: ['Swiss design (如确实是)'],
    tips: '非瑞士产禁用十字标'
  }
];

// 辅助函数：按分类获取词条
export function getWordsByCategory(categoryCode) {
  return RESTRICTED_WORDS_DATABASE.filter(w => w.category === categoryCode);
}

// 辅助函数：按风险等级获取词条
export function getWordsByRiskLevel(level) {
  return RESTRICTED_WORDS_DATABASE.filter(w => w.riskLevel === level);
}

// 辅助函数：按站点获取词条
export function getWordsBySite(siteCode) {
  return RESTRICTED_WORDS_DATABASE.filter(w => w.affectedSites.includes(siteCode));
}
